# 0. Install and Import Dependencies

In [ ]:
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python matplotlib

In [1]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

# 1. Load Model

In [2]:
#interpreter = tf.lite.Interpreter(model_path='../../models/lite-model_movenet_singlepose_lightning_3.tflite')
interpreter = tf.lite.Interpreter(model_path='../../models/lite-model_movenet_singlepose_thunder_3.tflite')
interpreter.allocate_tensors()

# 2. Make Detections

In [11]:
# Demo Function

interpreter = tf.lite.Interpreter(model_path='../../models/lite-model_movenet_singlepose_thunder_3.tflite')
interpreter.allocate_tensors()

cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 256,256)
    input_image = tf.cast(img, dtype=tf.float32)
    
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    cv2.imshow('MoveNet Lightning', frame)
    
    # Eye coordinates detection 
    left_eye = keypoints_with_scores[0][0][1]
    right_eye = keypoints_with_scores[0][0][2]

    left_eye_y = np.array(left_eye[:2]*[480,640]).astype(int)[0]
    right_eye_y = np.array(right_eye[:2]*[480,640]).astype(int)[0]
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()



[[[[0.53567064 0.57470244 0.7119747 ]
   [0.48267853 0.633958   0.75331044]
   [0.47202778 0.5278019  0.5656532 ]
   [0.5229252  0.69500864 0.56400895]
   [0.4942662  0.4767129  0.7376672 ]
   [0.6937462  0.7891383  0.598737  ]
   [0.69123554 0.33632347 0.8863464 ]
   [0.7544446  0.8695287  0.03176633]
   [0.75797075 0.26570913 0.01534992]
   [0.5149206  0.9085678  0.25567508]
   [0.6870849  0.29719225 0.01065934]
   [0.8277404  0.8236732  0.01152426]
   [0.5429418  0.83342475 0.02537319]
   [0.5284801  0.8829524  0.01216587]
   [0.7015536  0.3336249  0.06588849]
   [0.51560056 0.9065848  0.04995239]
   [0.44876236 0.48311737 0.02680048]]]]
[[[[0.52378434 0.57186645 0.75634545]
   [0.47293395 0.6264639  0.8022746 ]
   [0.4634106  0.5227106  0.7984853 ]
   [0.52198875 0.68699646 0.69631916]
   [0.502663   0.4687921  0.59020925]
   [0.69035345 0.7593525  0.65059775]
   [0.69492906 0.33180428 0.9057499 ]
   [0.75839776 0.88185847 0.05424678]
   [0.7578929  0.287887   0.00594714]
   [0.532

[[[[0.5170744  0.52332675 0.7485138 ]
   [0.4597238  0.5673388  0.86908114]
   [0.46699736 0.4698196  0.4406847 ]
   [0.49740142 0.63522834 0.75501347]
   [0.5166768  0.4232867  0.6350847 ]
   [0.68025696 0.7367413  0.80222774]
   [0.6991576  0.32301456 0.8246039 ]
   [0.79007995 0.97182196 0.07433325]
   [0.77503496 0.25960898 0.00455102]
   [0.53268766 0.8872461  0.5562993 ]
   [0.5061798  0.43326753 0.02923882]
   [0.8132066  0.8390728  0.01557404]
   [0.78860235 0.2945574  0.0111025 ]
   [0.5495296  0.87002134 0.01454002]
   [0.7126026  0.32196522 0.06278786]
   [0.534375   0.8882181  0.04426846]
   [0.44913906 0.42310685 0.01514322]]]]
[[[[0.5187414  0.52449083 0.78418636]
   [0.46115327 0.56768423 0.88509095]
   [0.46931553 0.47076437 0.5295051 ]
   [0.49511504 0.6362211  0.7737335 ]
   [0.51270735 0.42021078 0.61619407]
   [0.68220615 0.73600763 0.79108655]
   [0.6990634  0.3219181  0.8330132 ]
   [0.7971568  0.9771616  0.09459081]
   [0.7737627  0.2611133  0.00420436]
   [0.532

[[[[0.5267254  0.53034717 0.696674  ]
   [0.46577182 0.5793762  0.7221802 ]
   [0.47126547 0.48214084 0.7612915 ]
   [0.49799123 0.6466334  0.72221464]
   [0.51038915 0.43751395 0.6583827 ]
   [0.6878492  0.763644   0.6808573 ]
   [0.69432783 0.32874247 0.7026138 ]
   [0.7760155  0.9224497  0.02205655]
   [0.75897074 0.27688813 0.0043391 ]
   [0.55091    0.92537916 0.53448117]
   [0.6877509  0.2873489  0.00660813]
   [0.8148307  0.8513883  0.0154117 ]
   [0.79274666 0.30374378 0.00998017]
   [0.5562043  0.9096572  0.01728681]
   [0.70929784 0.3269828  0.05758312]
   [0.54779583 0.91923505 0.05460307]
   [0.45190632 0.43810016 0.01905519]]]]
[[[[0.52613807 0.5291313  0.7059484 ]
   [0.46634206 0.5816679  0.75128376]
   [0.4704169  0.4816882  0.7305198 ]
   [0.49955535 0.64557546 0.70458424]
   [0.50664866 0.43877417 0.6241389 ]
   [0.68839747 0.7722778  0.607812  ]
   [0.69184154 0.3279972  0.8534639 ]
   [0.7590598  0.8826412  0.01842782]
   [0.75934535 0.27690426 0.00509548]
   [0.547

[[[[0.5057313  0.5524717  0.60220927]
   [0.45977864 0.60630405 0.7236159 ]
   [0.45933807 0.50017774 0.7085088 ]
   [0.51874334 0.6729229  0.5682488 ]
   [0.49872208 0.4538201  0.6101102 ]
   [0.73081195 0.75587356 0.50650495]
   [0.68431556 0.33439532 0.5567386 ]
   [0.7645363  0.87231916 0.04794183]
   [0.7630632  0.23268516 0.01226783]
   [0.707432   0.76008934 0.56720126]
   [0.68991095 0.3466405  0.01301906]
   [0.80315596 0.79421604 0.01216048]
   [0.777021   0.26633492 0.01178351]
   [0.7243984  0.75286007 0.04870898]
   [0.67913    0.45889467 0.02815649]
   [0.7034692  0.7556494  0.01411673]
   [0.6543561  0.4722139  0.00746134]]]]
[[[[0.51093984 0.5567962  0.6037246 ]
   [0.46102217 0.60753626 0.6861607 ]
   [0.4601597  0.5045979  0.78924346]
   [0.51193583 0.6743875  0.68299866]
   [0.49668762 0.45599738 0.6456351 ]
   [0.7154927  0.7459599  0.54837096]
   [0.6834508  0.34289744 0.55846345]
   [0.76898515 0.87200403 0.03706869]
   [0.7614494  0.23673747 0.01253814]
   [0.701

[[[[0.49737093 0.5831481  0.733307  ]
   [0.4420954  0.64302343 0.7118918 ]
   [0.4253018  0.5281443  0.5297571 ]
   [0.48352164 0.6758319  0.68901396]
   [0.4525068  0.4500666  0.71015334]
   [0.6807711  0.7784484  0.6538636 ]
   [0.64552295 0.27243063 0.76271296]
   [0.4453335  0.68961596 0.0219512 ]
   [0.76198864 0.20003653 0.00407621]
   [0.76246244 0.844739   0.00764   ]
   [0.73739165 0.35481846 0.00517121]
   [0.36167657 0.6556056  0.01430669]
   [0.74196494 0.23634267 0.0300993 ]
   [0.6933147  0.7786809  0.00898835]
   [0.6625322  0.27266756 0.04411244]
   [0.42921853 0.6091529  0.03517571]
   [0.60770816 0.45531133 0.00378972]]]]
[[[[0.4927845  0.5738404  0.7526226 ]
   [0.4325358  0.6321133  0.8023087 ]
   [0.42336822 0.5185156  0.63430953]
   [0.46549007 0.6741362  0.6509975 ]
   [0.44538635 0.4416328  0.77034783]
   [0.6577004  0.7807671  0.5752406 ]
   [0.6345556  0.28266808 0.7903865 ]
   [0.41690198 0.6943605  0.02007675]
   [0.76528376 0.21791108 0.00457481]
   [0.757

[[[[0.5367505  0.52555496 0.73173743]
   [0.4912135  0.57966954 0.8052714 ]
   [0.47989488 0.4916018  0.7889187 ]
   [0.53340757 0.6355421  0.6926655 ]
   [0.49569792 0.4421212  0.72948325]
   [0.74993414 0.75512606 0.81867504]
   [0.71434176 0.3063511  0.69448024]
   [0.7593908  0.77629614 0.01511821]
   [0.77338827 0.24624938 0.0043664 ]
   [0.7327473  0.75792813 0.03134894]
   [0.4664901  0.445555   0.05232525]
   [0.48456222 0.80886036 0.0101172 ]
   [0.7969241  0.28212166 0.01044288]
   [0.76419014 0.7651623  0.03644046]
   [0.72401726 0.30863845 0.09358683]
   [0.68329424 0.66347736 0.00409079]
   [0.60795444 0.4873561  0.00211704]]]]
[[[[0.53700787 0.53143376 0.6121837 ]
   [0.49065942 0.58293307 0.86244947]
   [0.48048058 0.4933201  0.8013141 ]
   [0.5280311  0.64002043 0.6171752 ]
   [0.4989992  0.44230634 0.7367841 ]
   [0.74250436 0.7542552  0.84982693]
   [0.7152729  0.30516195 0.9009047 ]
   [0.7560142  0.774859   0.02036881]
   [0.7729662  0.24792801 0.00457981]
   [0.728

[[[[0.548306   0.5380377  0.6899938 ]
   [0.4891317  0.59441173 0.77171755]
   [0.48265827 0.49090752 0.59026486]
   [0.52007985 0.65203273 0.7334627 ]
   [0.5004406  0.43874854 0.49053714]
   [0.72251624 0.76745594 0.7677469 ]
   [0.6950731  0.30794942 0.7932168 ]
   [0.7567308  0.8445704  0.04459712]
   [0.77316064 0.23830947 0.00509351]
   [0.7556025  0.84700114 0.04348978]
   [0.75894266 0.32096636 0.00416431]
   [0.46227837 0.82027954 0.01586568]
   [0.41420296 0.8133225  0.05159315]
   [0.740198   0.7689374  0.00836134]
   [0.705906   0.30639607 0.05662516]
   [0.47591192 0.5771915  0.03999913]
   [0.6249626  0.51097083 0.00413796]]]]
[[[[0.54735833 0.5384407  0.6648945 ]
   [0.4895411  0.59602994 0.8149196 ]
   [0.48277384 0.49087462 0.5983399 ]
   [0.5231095  0.65097046 0.539849  ]
   [0.49849454 0.43898618 0.46406013]
   [0.7283732  0.76910335 0.7526753 ]
   [0.69389355 0.30686036 0.8622019 ]
   [0.7614976  0.8530257  0.04704145]
   [0.7725524  0.23533319 0.00406104]
   [0.706

[[[[0.5616261  0.56845146 0.6568523 ]
   [0.51490647 0.6227316  0.47737166]
   [0.49582484 0.5213685  0.7466381 ]
   [0.55045646 0.6658605  0.7197819 ]
   [0.5140249  0.45480442 0.50786006]
   [0.72445494 0.76716894 0.6444738 ]
   [0.69407046 0.31488517 0.73308045]
   [0.75781155 0.8443302  0.0461289 ]
   [0.7745158  0.22106762 0.0040665 ]
   [0.7570194  0.8380964  0.0366331 ]
   [0.757376   0.33769223 0.00444785]
   [0.8318524  0.79692847 0.00691241]
   [0.79171133 0.27598912 0.00668761]
   [0.7435281  0.7803522  0.01063579]
   [0.70243007 0.31512308 0.06765342]
   [0.53622097 0.6176433  0.02414754]
   [0.6571919  0.5245414  0.0070968 ]]]]
[[[[0.56187505 0.56974846 0.6566546 ]
   [0.515033   0.62449706 0.5170735 ]
   [0.4956669  0.52282983 0.82842594]
   [0.55179507 0.6668379  0.7323129 ]
   [0.51400566 0.45517206 0.49702865]
   [0.72556365 0.7654045  0.6369271 ]
   [0.6919321  0.3136128  0.6846008 ]
   [0.7596106  0.8435658  0.04521286]
   [0.77022386 0.23533118 0.00351745]
   [0.759

[[[[0.49916965 0.58607954 0.6287123 ]
   [0.4614511  0.6415114  0.7746852 ]
   [0.43717924 0.5428417  0.7524269 ]
   [0.52617264 0.67997265 0.81328094]
   [0.47061935 0.47216758 0.68324023]
   [0.72810733 0.78489757 0.8146279 ]
   [0.68626803 0.3096425  0.92583275]
   [0.776198   0.86627114 0.01639542]
   [0.7755202  0.2419877  0.00423044]
   [0.73215646 0.78393626 0.03330591]
   [0.7117361  0.33915848 0.0029155 ]
   [0.85597885 0.76932293 0.00460821]
   [0.79068863 0.27801362 0.00734755]
   [0.7474551  0.7903167  0.03137991]
   [0.6957146  0.30943498 0.04616743]
   [0.45851123 0.6135442  0.02500737]
   [0.4178319  0.48366505 0.00594297]]]]
[[[[0.49605492 0.5846296  0.5495308 ]
   [0.46177343 0.64071256 0.78966975]
   [0.4368452  0.5441494  0.7525135 ]
   [0.5281162  0.67761874 0.7556186 ]
   [0.47052568 0.47337127 0.7154147 ]
   [0.72388273 0.79217625 0.7369895 ]
   [0.6826244  0.31252557 0.9344673 ]
   [0.7480049  0.97372967 0.03806427]
   [0.76963395 0.23050511 0.00378805]
   [0.764

[[[[0.54465747 0.56913    0.7461546 ]
   [0.48793668 0.62180877 0.71047115]
   [0.47808728 0.52092737 0.8504244 ]
   [0.5235506  0.67766196 0.751778  ]
   [0.50470406 0.46606892 0.5679229 ]
   [0.7260554  0.7907734  0.63822234]
   [0.6990252  0.32863316 0.8233124 ]
   [0.75665534 0.8559673  0.02138978]
   [0.47709733 0.48290473 0.02778766]
   [0.74301714 0.85610735 0.02820027]
   [0.76086766 0.3950136  0.00550398]
   [0.8542742  0.74556166 0.00286943]
   [0.4565162  0.834539   0.02800792]
   [0.74260813 0.8079747  0.00780493]
   [0.7113974  0.3264161  0.05624238]
   [0.6917574  0.7282184  0.00549385]
   [0.64473736 0.52962214 0.00313899]]]]
[[[[0.5417139  0.567887   0.73981726]
   [0.4868187  0.62072635 0.7124709 ]
   [0.47662362 0.5210943  0.8672191 ]
   [0.52241    0.6774409  0.73545545]
   [0.50376755 0.46669963 0.55874324]
   [0.7250878  0.788677   0.65118575]
   [0.6972639  0.32749352 0.80746573]
   [0.75710255 0.8550276  0.02576846]
   [0.7667871  0.2793939  0.00708857]
   [0.749

[[[[0.5538957  0.54748154 0.55051154]
   [0.49016932 0.5992307  0.8094797 ]
   [0.4802129  0.49642742 0.6226142 ]
   [0.5108917  0.64752847 0.7216042 ]
   [0.49869797 0.4350994  0.5452046 ]
   [0.7290122  0.77873194 0.49486694]
   [0.72259754 0.27336484 0.55131674]
   [0.7831816  0.9190923  0.03556359]
   [0.77037764 0.09135364 0.05347049]
   [0.5977312  0.6606721  0.09910363]
   [0.559833   0.2694692  0.13349894]
   [0.7886029  0.9069789  0.01937714]
   [0.9977113  0.33584523 0.00174534]
   [0.75245386 0.85369164 0.01448441]
   [0.47917187 0.2315849  0.02774632]
   [0.5552729  0.6673059  0.03066495]
   [0.45488617 0.43929002 0.01787418]]]]
[[[[0.54623944 0.54306275 0.643436  ]
   [0.48825994 0.58945656 0.7571665 ]
   [0.48349044 0.49538192 0.6458522 ]
   [0.5125113  0.6386182  0.77951145]
   [0.5020437  0.4433994  0.6020455 ]
   [0.69434613 0.74945354 0.70983315]
   [0.7103526  0.31604704 0.5864025 ]
   [0.7802292  0.89311427 0.01213565]
   [0.7635791  0.2515507  0.0179694 ]
   [0.567

[[[[0.5369657  0.55409575 0.6627184 ]
   [0.4858839  0.5952862  0.64427316]
   [0.47951505 0.5086543  0.7484329 ]
   [0.5204891  0.63475376 0.6552102 ]
   [0.50464225 0.4524771  0.54736483]
   [0.68003523 0.730019   0.60762316]
   [0.6818392  0.34208173 0.5287352 ]
   [0.7382348  0.8970292  0.12791449]
   [0.7405031  0.21022119 0.30050227]
   [0.44269544 0.78819346 0.16842765]
   [0.56480837 0.33954194 0.05811679]
   [0.80477023 0.86769867 0.03599152]
   [0.7850118  0.31552383 0.0197691 ]
   [0.4807931  0.3354676  0.0536786 ]
   [0.6295607  0.35185882 0.02244902]
   [0.4957848  0.3225702  0.06921718]
   [0.54884917 0.35297862 0.02207714]]]]
[[[[0.5350738  0.55427223 0.67833865]
   [0.48596686 0.5986178  0.69758606]
   [0.47687316 0.5104877  0.7880193 ]
   [0.5216369  0.6379782  0.6241356 ]
   [0.5024757  0.45255995 0.6063794 ]
   [0.6872531  0.740157   0.6117961 ]
   [0.71399575 0.34904805 0.58242047]
   [0.7540196  0.91144717 0.06834728]
   [0.7175795  0.31628478 0.01285195]
   [0.458

[[[[0.53155136 0.5653886  0.5896262 ]
   [0.48426306 0.6059946  0.49654284]
   [0.4790621  0.51951885 0.77266204]
   [0.51277065 0.6460426  0.78502864]
   [0.49550554 0.4721657  0.5383249 ]
   [0.7064108  0.7464609  0.59691733]
   [0.7038696  0.3240025  0.6756528 ]
   [0.7591633  0.923477   0.0623332 ]
   [0.75479764 0.19648692 0.06177941]
   [0.5135412  0.6543158  0.07257363]
   [0.7029442  0.25289086 0.20115274]
   [0.8109069  0.8616954  0.01730889]
   [0.76932013 0.03113267 0.02231005]
   [0.38686612 0.22709076 0.09687519]
   [0.69468063 0.27961692 0.03881603]
   [0.431239   0.3237171  0.06887892]
   [0.65605795 0.11083525 0.06428376]]]]
[[[[0.52371883 0.5508089  0.76068205]
   [0.48073187 0.59800684 0.83599865]
   [0.47342274 0.51032513 0.82764393]
   [0.5233637  0.65222794 0.8058342 ]
   [0.5007034  0.45822927 0.62890536]
   [0.7168824  0.7786541  0.7898614 ]
   [0.7049715  0.32220703 0.7840712 ]
   [0.7442239  0.832989   0.02170122]
   [0.7467868  0.16714406 0.15687692]
   [0.735

[[[[0.5627857  0.5490111  0.49254844]
   [0.50627893 0.5889223  0.6927208 ]
   [0.50450337 0.50274366 0.6943139 ]
   [0.51337415 0.64297587 0.6400404 ]
   [0.5054809  0.44967303 0.7118702 ]
   [0.70199984 0.70268357 0.82810056]
   [0.69646657 0.33500215 0.7228833 ]
   [0.6804872  0.7873136  0.04715994]
   [0.77268755 0.2732     0.10815907]
   [0.6792792  0.78062457 0.76349074]
   [0.6803547  0.31644514 0.6585937 ]
   [0.47204968 0.4210928  0.01545596]
   [0.80029106 0.28085297 0.0108175 ]
   [0.7153288  0.70793325 0.02567351]
   [0.6972461  0.3222451  0.10345012]
   [0.67590415 0.77543306 0.01556966]
   [0.67731017 0.3145861  0.05451646]]]]
[[[[0.5731843  0.54441786 0.6606698 ]
   [0.51057863 0.58969903 0.66113   ]
   [0.50959903 0.4958977  0.64490694]
   [0.5158943  0.6421986  0.67806923]
   [0.5120519  0.44258708 0.6745119 ]
   [0.70863056 0.70128596 0.8425445 ]
   [0.7098589  0.33539736 0.69774956]
   [0.67606807 0.7830747  0.03521633]
   [0.7748417  0.27262828 0.09446639]
   [0.676

[[[[0.56784856 0.5421678  0.6357852 ]
   [0.51045716 0.5868056  0.65912586]
   [0.5085686  0.49140215 0.7308896 ]
   [0.52661973 0.63332987 0.65760547]
   [0.5153597  0.43216562 0.56314945]
   [0.7112822  0.68727267 0.8642417 ]
   [0.7073722  0.31041855 0.54078835]
   [0.6793332  0.78693664 0.06613132]
   [0.77862835 0.26524362 0.06406853]
   [0.6765862  0.78276205 0.73967886]
   [0.68391234 0.31672144 0.66346675]
   [0.50261956 0.40035257 0.02772081]
   [0.79773664 0.26716805 0.01735723]
   [0.72387415 0.6955876  0.01699904]
   [0.71061224 0.31302264 0.06532142]
   [0.48674148 0.5602984  0.02608806]
   [0.6815639  0.3054479  0.0562703 ]]]]
[[[[0.57106614 0.5402234  0.6495616 ]
   [0.5160976  0.5902231  0.4963482 ]
   [0.5101889  0.49099797 0.75488937]
   [0.53240824 0.63562167 0.5900417 ]
   [0.517157   0.42975596 0.57830817]
   [0.7127218  0.68849796 0.8466956 ]
   [0.7059312  0.30767342 0.5830522 ]
   [0.760619   0.8044551  0.03367373]
   [0.77992344 0.2634842  0.06558236]
   [0.673

[[[[0.57369804 0.5410882  0.5908127 ]
   [0.5108433  0.58866256 0.7185031 ]
   [0.51383436 0.49052253 0.66612375]
   [0.5249042  0.63168156 0.6743526 ]
   [0.52287775 0.42185393 0.4593564 ]
   [0.7168796  0.69193995 0.6436719 ]
   [0.71013397 0.30931255 0.60923034]
   [0.69620323 0.7954573  0.08030912]
   [0.7760527  0.25211662 0.08029723]
   [0.69282377 0.7937014  0.7273909 ]
   [0.7001494  0.29314652 0.50319695]
   [0.5061555  0.40654734 0.02893016]
   [0.79703254 0.2655789  0.01376411]
   [0.7358706  0.7033365  0.00784868]
   [0.7145325  0.30384383 0.07105589]
   [0.49151394 0.56290346 0.02634925]
   [0.69531095 0.28959522 0.0578137 ]]]]
[[[[0.5791523  0.5335655  0.5687701 ]
   [0.51599514 0.5819974  0.6867299 ]
   [0.512799   0.48093474 0.6492085 ]
   [0.53193647 0.630465   0.655931  ]
   [0.5235543  0.41416517 0.6798851 ]
   [0.7167753  0.69843906 0.78600883]
   [0.7060707  0.3144904  0.495303  ]
   [0.7527535  0.8022842  0.0785118 ]
   [0.7775923  0.25308272 0.11282867]
   [0.680

[[[[0.57489616 0.54400945 0.662411  ]
   [0.51726615 0.5892864  0.66647506]
   [0.51476485 0.49375    0.6435498 ]
   [0.5307154  0.64177155 0.58283836]
   [0.5247247  0.4310172  0.64849555]
   [0.71792096 0.70419365 0.6239874 ]
   [0.7137559  0.31076452 0.6730067 ]
   [0.6961202  0.81174237 0.04791397]
   [0.77176994 0.25779432 0.06074536]
   [0.68695104 0.80592906 0.56314117]
   [0.6975865  0.30172682 0.44933665]
   [0.4799748  0.42466724 0.03760311]
   [0.7809567  0.26552746 0.02206612]
   [0.7338251  0.71377814 0.01046902]
   [0.73506373 0.33527383 0.08274704]
   [0.49538028 0.5728396  0.03729236]
   [0.6946674  0.29246065 0.08803427]]]]
[[[[0.5738642  0.54333216 0.66046804]
   [0.5168102  0.59026194 0.58529675]
   [0.51324564 0.49430677 0.73593676]
   [0.5252254  0.641131   0.67837334]
   [0.51296926 0.43723843 0.5124386 ]
   [0.7183592  0.71003264 0.6903592 ]
   [0.7052312  0.3219769  0.62471473]
   [0.7031456  0.81674105 0.07140124]
   [0.77014536 0.2558387  0.05372828]
   [0.700

[[[[0.57423717 0.5425776  0.710845  ]
   [0.51922107 0.5961785  0.75847334]
   [0.5150978  0.5007287  0.4146936 ]
   [0.54065955 0.6509935  0.5808248 ]
   [0.5245703  0.4456498  0.74230415]
   [0.7306712  0.74735165 0.63588387]
   [0.69700724 0.3209177  0.8616688 ]
   [0.7690383  0.89789504 0.02091527]
   [0.77490133 0.2587781  0.005362  ]
   [0.7338983  0.77294356 0.02018335]
   [0.50990367 0.46179903 0.02784488]
   [0.8265893  0.77600604 0.00895333]
   [0.7783774  0.29121688 0.01360589]
   [0.73926973 0.7589009  0.01333421]
   [0.71261317 0.3202409  0.03286761]
   [0.50488394 0.5762997  0.04985648]
   [0.67612207 0.49326232 0.00671932]]]]
[[[[0.5797616  0.5453707  0.6440774 ]
   [0.5222996  0.5984509  0.8223691 ]
   [0.51644003 0.50152636 0.54024357]
   [0.5397513  0.6561099  0.6555864 ]
   [0.5195784  0.44709766 0.69344103]
   [0.72685647 0.7460012  0.60860145]
   [0.70234764 0.32148242 0.8771241 ]
   [0.7650617  0.83692604 0.01652271]
   [0.7753463  0.25918356 0.00326842]
   [0.742

[[[[0.5720815  0.5510476  0.6900839 ]
   [0.5132661  0.60148406 0.7429652 ]
   [0.5077347  0.50288    0.753507  ]
   [0.5362539  0.6555994  0.6135174 ]
   [0.52316356 0.44812942 0.748106  ]
   [0.727619   0.7401939  0.67846406]
   [0.70031744 0.32296258 0.83340013]
   [0.7516567  0.84986687 0.10357717]
   [0.77150965 0.27079946 0.00356588]
   [0.75267464 0.8491424  0.34663117]
   [0.64553756 0.5112795  0.02284279]
   [0.87818956 0.7165213  0.0037576 ]
   [0.78576493 0.3060209  0.00845644]
   [0.7517923  0.74789673 0.01088852]
   [0.7123558  0.32292783 0.0686112 ]
   [0.49757743 0.58180153 0.03916261]
   [0.6904484  0.51319236 0.00333863]]]]
[[[[0.57053566 0.5523949  0.7119967 ]
   [0.51228094 0.6032224  0.759174  ]
   [0.5064223  0.50403225 0.77160424]
   [0.54005545 0.6579061  0.6694353 ]
   [0.52345395 0.4476498  0.7696014 ]
   [0.7268666  0.743431   0.7229274 ]
   [0.697586   0.32316905 0.871456  ]
   [0.7491656  0.86149484 0.12091863]
   [0.7677573  0.28160638 0.00329274]
   [0.754

[[[[0.57125646 0.5530554  0.71991354]
   [0.51886326 0.60339934 0.7101943 ]
   [0.51215565 0.50854534 0.7632328 ]
   [0.54424864 0.65892935 0.6933328 ]
   [0.5278526  0.45030087 0.68974775]
   [0.73360837 0.7562201  0.5269309 ]
   [0.69866073 0.32313812 0.7965567 ]
   [0.7457477  0.8559192  0.05568993]
   [0.77396625 0.2602557  0.00463113]
   [0.69344103 0.8658787  0.12036291]
   [0.7688714  0.33654675 0.00324312]
   [0.82114655 0.7759523  0.00985703]
   [0.79061985 0.29515508 0.00869381]
   [0.71214926 0.81976753 0.02043748]
   [0.7112678  0.3226041  0.07729024]
   [0.5079348  0.5920572  0.03690532]
   [0.649887   0.522184   0.0037061 ]]]]
[[[[0.57221746 0.5533273  0.72899103]
   [0.5175535  0.60313416 0.71223515]
   [0.51142776 0.5076327  0.78176427]
   [0.539841   0.6571684  0.6649107 ]
   [0.5280922  0.448591   0.7034894 ]
   [0.73425794 0.7540908  0.5729378 ]
   [0.6996171  0.322979   0.78193736]
   [0.7507448  0.8378127  0.02442712]
   [0.7731944  0.25949842 0.00438163]
   [0.693

[[[[0.57153416 0.52628994 0.6960422 ]
   [0.5098616  0.58310354 0.8322274 ]
   [0.5054309  0.48121578 0.80064774]
   [0.5374593  0.64371544 0.6724809 ]
   [0.52417237 0.43361795 0.71660954]
   [0.7297481  0.74942124 0.7283602 ]
   [0.7031736  0.3174153  0.73064125]
   [0.76147586 0.89592475 0.0173794 ]
   [0.5094985  0.44942445 0.02101442]
   [0.7356492  0.7260353  0.02238116]
   [0.49192694 0.44695967 0.03848472]
   [0.47499135 0.83144367 0.01783347]
   [0.79249495 0.29422122 0.01346359]
   [0.7447681  0.75590533 0.01504967]
   [0.7150558  0.31743726 0.03741863]
   [0.49795502 0.56129396 0.04036176]
   [0.6915705  0.4884902  0.00456551]]]]
[[[[0.5697272  0.5268842  0.72179216]
   [0.5082214  0.5820501  0.84359956]
   [0.5047251  0.48092592 0.8159299 ]
   [0.5327786  0.64268863 0.6750339 ]
   [0.52388394 0.43166146 0.72821057]
   [0.73432845 0.7509548  0.7937658 ]
   [0.7004482  0.31871396 0.8303913 ]
   [0.49909955 0.66252285 0.03889576]
   [0.50524014 0.43735814 0.02361262]
   [0.733

[[[[0.52475744 0.5168545  0.6727053 ]
   [0.47508758 0.5674242  0.8187151 ]
   [0.4593032  0.47212353 0.81196594]
   [0.51716274 0.6170522  0.7289324 ]
   [0.4954059  0.40881026 0.7401892 ]
   [0.73403823 0.72333795 0.8918327 ]
   [0.691301   0.26367787 0.7287644 ]
   [0.7454521  0.7461757  0.01313007]
   [0.77530736 0.19457513 0.00454023]
   [0.74501383 0.73791885 0.0161235 ]
   [0.7527366  0.2917044  0.00459975]
   [0.84974885 0.68500316 0.00365046]
   [0.77834386 0.24214102 0.01362291]
   [0.7480001  0.7302202  0.02742466]
   [0.70228946 0.26511088 0.08625135]
   [0.664578   0.648596   0.00380218]
   [0.64057267 0.44397572 0.00368327]]]]
[[[[0.5340006  0.51168567 0.65716386]
   [0.47974116 0.56426096 0.7504601 ]
   [0.46594942 0.46701115 0.5528803 ]
   [0.51549524 0.61678404 0.7302166 ]
   [0.49424985 0.4065292  0.657553  ]
   [0.73493224 0.7222527  0.87842476]
   [0.69399464 0.26489633 0.77929187]
   [0.47872534 0.63289404 0.02432537]
   [0.4499999  0.40113878 0.03480759]
   [0.729

[[[[0.55110645 0.55176795 0.40143454]
   [0.5420776  0.61249083 0.7746619 ]
   [0.4864598  0.54144734 0.6815365 ]
   [0.587107   0.62884647 0.64355254]
   [0.467379   0.4633619  0.6780564 ]
   [0.72594684 0.66675663 0.7129063 ]
   [0.6890201  0.25271764 0.83440727]
   [0.97709036 0.6757682  0.00503719]
   [0.44848663 0.47811097 0.02408296]
   [0.6691341  0.74282223 0.02929476]
   [0.46782324 0.4584681  0.04340437]
   [0.9383828  1.000325   0.01185057]
   [0.778798   0.2159476  0.00814185]
   [0.74868244 0.68278635 0.02721253]
   [0.6996896  0.25270078 0.05219838]
   [0.5698189  0.64348376 0.02135181]
   [0.45882452 0.45574975 0.00651872]]]]
[[[[0.55032766 0.55714595 0.5077253 ]
   [0.54131484 0.61373514 0.80228627]
   [0.48423538 0.54165596 0.6365813 ]
   [0.5867322  0.62625223 0.61579764]
   [0.46572292 0.46281606 0.67307615]
   [0.7285813  0.66858923 0.86434567]
   [0.6870743  0.25092185 0.87173826]
   [0.77015597 0.74147344 0.03307396]
   [0.44483033 0.47621137 0.02866521]
   [0.750

[[[[ 0.5670931   0.5618939   0.44471908]
   [ 0.56066304  0.61587644  0.6739085 ]
   [ 0.5037711   0.55378497  0.730437  ]
   [ 0.5915622   0.62810713  0.5359192 ]
   [ 0.47468543  0.4746902   0.674152  ]
   [ 0.73150593  0.6660469   0.76061225]
   [ 0.6880944   0.25645116  0.8578128 ]
   [ 0.76913655  0.7119596   0.04381192]
   [ 0.46263972  0.48678416  0.0216234 ]
   [ 0.7396269   0.7380672   0.02056077]
   [ 0.74099976  0.3381952   0.01600203]
   [ 0.7620557  -0.0042839   0.00529847]
   [ 0.77543557  0.22720447  0.01077971]
   [ 0.76063204  0.68155134  0.02875814]
   [ 0.6980993   0.25687814  0.0567959 ]
   [ 0.5790734   0.6195398   0.01297218]
   [ 0.6771742   0.40782622  0.00364482]]]]
[[[[0.59966767 0.5740145  0.50087816]
   [0.58980954 0.62254155 0.58928   ]
   [0.53397816 0.5679583  0.6063694 ]
   [0.6105994  0.6343806  0.6535902 ]
   [0.48869902 0.4889987  0.61325634]
   [0.7374118  0.6632989  0.69690293]
   [0.6878398  0.25961423 0.8367342 ]
   [0.7659921  0.70646226 0.046731

[[[[0.5876834  0.5738066  0.50304127]
   [0.57637113 0.621532   0.7017089 ]
   [0.5215896  0.5604912  0.6804695 ]
   [0.6123828  0.63412684 0.65985173]
   [0.4996624  0.47955787 0.6017964 ]
   [0.7408988  0.6648355  0.853041  ]
   [0.6893985  0.26916897 0.8424438 ]
   [0.9539603  0.6803103  0.00550982]
   [0.49070033 0.4929565  0.02024141]
   [0.98710793 0.6478075  0.0160189 ]
   [0.5091638  0.48932284 0.03605059]
   [0.9862352  0.68819547 0.00717315]
   [0.7775588  0.22859593 0.00745448]
   [0.7642796  0.6797036  0.06726426]
   [0.69565433 0.26981017 0.05169651]
   [0.59576803 0.59414405 0.01743892]
   [0.67424226 0.42422134 0.00503328]]]]
[[[[0.5868128  0.5754132  0.4722946 ]
   [0.5766608  0.6235458  0.6526052 ]
   [0.5194156  0.5613409  0.6642217 ]
   [0.6112095  0.6355982  0.6648813 ]
   [0.4980342  0.4819876  0.5985131 ]
   [0.7402691  0.6653696  0.848817  ]
   [0.6900193  0.26807567 0.8474002 ]
   [0.77077556 0.71511805 0.04289249]
   [0.480032   0.4932583  0.02403879]
   [0.984

[[[[0.578526   0.5644665  0.37252676]
   [0.5647165  0.619749   0.6844435 ]
   [0.51420426 0.5473131  0.5630777 ]
   [0.6093651  0.63193923 0.6104167 ]
   [0.49903706 0.46557486 0.5962389 ]
   [0.74783164 0.6746854  0.7358363 ]
   [0.7016056  0.26782572 0.8839797 ]
   [0.9751465  0.6998437  0.00757766]
   [0.4853151  0.47566    0.02585757]
   [0.9873593  0.665175   0.01306352]
   [0.49850076 0.4736016  0.04053831]
   [0.9835688  0.69950384 0.00930133]
   [0.78822076 0.22607392 0.00982666]
   [0.7698848  0.68806005 0.03725111]
   [0.70736605 0.26900256 0.04678831]
   [0.57831657 0.58546233 0.02476457]
   [0.67809933 0.42620274 0.00557068]]]]
[[[[0.5799556  0.56452817 0.42112607]
   [0.56510246 0.6203171  0.68576455]
   [0.5132883  0.5462199  0.56071794]
   [0.61031115 0.63501537 0.6345394 ]
   [0.4990716  0.4639777  0.62824863]
   [0.75294846 0.6782767  0.8480048 ]
   [0.70287204 0.26308712 0.8746643 ]
   [0.7731828  0.7144087  0.03387424]
   [0.48388147 0.4776698  0.02327108]
   [0.765

[[[[0.568648   0.53385097 0.59122735]
   [0.5509146  0.59255266 0.6572101 ]
   [0.50460464 0.51186013 0.76772434]
   [0.5942314  0.6107044  0.5824263 ]
   [0.49886075 0.4485763  0.6082791 ]
   [0.74798906 0.66897386 0.7659296 ]
   [0.6784801  0.17778973 0.5091498 ]
   [0.77042556 0.71033365 0.03807819]
   [0.69377095 0.10481708 0.0571447 ]
   [0.7626609  0.7111948  0.01991257]
   [0.6821722  0.2672521  0.01103452]
   [0.7686445  0.03622578 0.01265511]
   [0.7073564  0.13164781 0.020989  ]
   [0.76970255 0.6845661  0.02587003]
   [0.6853982  0.13976584 0.04471636]
   [0.54156584 0.5483963  0.05027643]
   [0.48228508 0.44619963 0.00796035]]]]
[[[[0.57236683 0.53682464 0.5476151 ]
   [0.55078477 0.59402657 0.65959907]
   [0.50752646 0.513604   0.73218393]
   [0.5910879  0.6081308  0.5250122 ]
   [0.4984801  0.44900706 0.62256753]
   [0.750108   0.6692782  0.79956114]
   [0.66124606 0.23259193 0.43389648]
   [0.7699337  0.7026908  0.03178284]
   [0.6138282  0.11509883 0.07868597]
   [0.761

[[[[0.56095326 0.5223377  0.49869978]
   [0.53869236 0.58241427 0.7798152 ]
   [0.50145876 0.49962366 0.6881122 ]
   [0.58693844 0.61055386 0.66917413]
   [0.5050607  0.4423116  0.6444359 ]
   [0.7463095  0.67863804 0.78012604]
   [0.6977967  0.25493032 0.8190738 ]
   [0.7679171  0.7134149  0.03036296]
   [0.47287497 0.42658174 0.02856675]
   [0.7588108  0.7093988  0.02171636]
   [0.4892912  0.44857416 0.06040329]
   [0.7762364  0.17443182 0.01581496]
   [0.766004   0.18537273 0.02502263]
   [0.76932627 0.69199204 0.02381635]
   [0.70092803 0.25455025 0.03708869]
   [0.5144541  0.53644216 0.03528425]
   [0.4794561  0.43289012 0.01131335]]]]
[[[[0.5634547  0.5225738  0.55855   ]
   [0.54330254 0.58333015 0.7221674 ]
   [0.50255895 0.50292593 0.705055  ]
   [0.58984613 0.606013   0.5744683 ]
   [0.4957045  0.44177508 0.67205846]
   [0.7450969  0.6731048  0.7218901 ]
   [0.70167834 0.26002654 0.6895168 ]
   [0.9782722  0.69509786 0.00608671]
   [0.7316858  0.07144418 0.0452677 ]
   [0.760

[[[[0.5571935  0.5121515  0.5506433 ]
   [0.53370124 0.5694882  0.68574095]
   [0.50010514 0.4886604  0.6428348 ]
   [0.5818439  0.6040825  0.65633124]
   [0.5042894  0.43461767 0.70025694]
   [0.7397973  0.6706256  0.85383147]
   [0.709757   0.26896137 0.8331613 ]
   [0.98886746 0.6992768  0.01035908]
   [0.47173613 0.42035112 0.04232556]
   [0.73443127 0.66537005 0.01184258]
   [0.49592316 0.43434227 0.08803132]
   [1.0102059  0.6642994  0.00365838]
   [0.801689   0.2551496  0.00380906]
   [0.75991094 0.6861257  0.01991805]
   [0.71574306 0.27166042 0.038661  ]
   [0.5698492  0.578928   0.01149169]
   [0.48158562 0.42846513 0.01211524]]]]
[[[[0.56028235 0.519885   0.5601353 ]
   [0.53444755 0.5743336  0.63949466]
   [0.501314   0.49312824 0.70339465]
   [0.5796797  0.6037335  0.6467823 ]
   [0.5063136  0.43500698 0.7473575 ]
   [0.73804    0.6736121  0.85393417]
   [0.7087149  0.26673034 0.84251904]
   [0.98639566 0.7027943  0.01520631]
   [0.47552592 0.4268561  0.04077286]
   [0.762

[[[[0.5711395  0.48172072 0.61639804]
   [0.5319808  0.54545975 0.57317716]
   [0.5066955  0.45409408 0.74859166]
   [0.57392776 0.60126024 0.7190031 ]
   [0.51773226 0.41110995 0.52390206]
   [0.7452763  0.693431   0.78413033]
   [0.7132059  0.26770005 0.7964709 ]
   [0.99020636 0.6986239  0.00730383]
   [0.49434516 0.41324857 0.03355962]
   [0.6040194  0.5263156  0.03669909]
   [0.4860972  0.41123492 0.08449847]
   [0.9826365  0.704075   0.00269961]
   [0.79635334 0.2423855  0.00596702]
   [0.7633565  0.70454776 0.01899123]
   [0.72693694 0.26858988 0.02678886]
   [0.68667245 0.58702445 0.00457081]
   [0.47765654 0.4050847  0.03567204]]]]
[[[[0.5711057  0.47994027 0.65114236]
   [0.5284655  0.5405691  0.7771853 ]
   [0.50657266 0.4499719  0.71809644]
   [0.57041675 0.5990445  0.73648864]
   [0.5223593  0.4085468  0.5766344 ]
   [0.7449543  0.6939656  0.7801316 ]
   [0.7131331  0.27311867 0.7784408 ]
   [0.9897568  0.7007866  0.00864992]
   [0.4978295  0.4144823  0.03116187]
   [0.603

[[[[ 0.56920063  0.4580523   0.6861377 ]
   [ 0.50881433  0.50792074  0.8390186 ]
   [ 0.5119335   0.41296238  0.7722033 ]
   [ 0.5360304   0.5730986   0.49983004]
   [ 0.53848886  0.37427804  0.6192618 ]
   [ 0.729772    0.6974436   0.8258848 ]
   [ 0.7257566   0.27166983  0.80660576]
   [ 0.5322637   0.5864282   0.02301961]
   [ 0.75771475  0.2316372   0.01900053]
   [ 0.735779    0.6816449   0.01286107]
   [ 0.75965846  0.22658558  0.01626596]
   [-0.02172296  0.964377    0.02078962]
   [ 0.7938422   0.247315    0.01329234]
   [ 0.74934095  0.711301    0.00965053]
   [ 0.7369573   0.2717432   0.10179397]
   [ 0.5039102   0.4883492   0.02282214]
   [ 0.48299092  0.37742168  0.03675175]]]]
[[[[0.5693722  0.45889035 0.7103969 ]
   [0.5110272  0.5102835  0.8318927 ]
   [0.51268756 0.41313884 0.7347723 ]
   [0.53755045 0.5757075  0.5745813 ]
   [0.5386312  0.37370756 0.62034005]
   [0.735563   0.70642227 0.8710087 ]
   [0.7191761  0.2748428  0.790969  ]
   [0.5341666  0.58300406 0.022255

[[[[0.58409977 0.46481052 0.7419311 ]
   [0.5216047  0.51730937 0.7408919 ]
   [0.51945764 0.42375383 0.69945794]
   [0.5357467  0.57682663 0.5856959 ]
   [0.53703344 0.3774208  0.67038053]
   [0.7302085  0.6997932  0.7895975 ]
   [0.7254986  0.2698301  0.822706  ]
   [0.5106132  0.5975087  0.04611742]
   [0.75877404 0.23080975 0.00933436]
   [0.7185181  0.6794495  0.02062178]
   [0.50512064 0.38700852 0.05686563]
   [0.91939676 0.9858678  0.00854042]
   [0.79282176 0.24643415 0.01339582]
   [0.7449494  0.71124244 0.01042327]
   [0.73790026 0.27008477 0.10192919]
   [0.5095065  0.49782208 0.03002214]
   [0.7048402  0.4436069  0.00759935]]]]
[[[[0.5836373  0.46587956 0.7383356 ]
   [0.52216023 0.51817715 0.7656378 ]
   [0.5180487  0.42410475 0.6802674 ]
   [0.5372713  0.5753743  0.55639327]
   [0.53485185 0.37660313 0.59268475]
   [0.7303229  0.70120734 0.8450906 ]
   [0.7240701  0.2646963  0.7817146 ]
   [0.51195836 0.5986639  0.05678403]
   [0.75809115 0.23467246 0.00936154]
   [0.582

[[[[ 0.5628514   0.47188535  0.5941577 ]
   [ 0.50987965  0.52111036  0.8195697 ]
   [ 0.50374895  0.4342545   0.7632041 ]
   [ 0.5460708   0.57573116  0.5350335 ]
   [ 0.5334153   0.3908522   0.50621384]
   [ 0.7307172   0.7049656   0.7938981 ]
   [ 0.718337    0.2793601   0.7996769 ]
   [ 0.51188356  0.5971731   0.03983214]
   [ 0.5042923   0.40200675  0.02999502]
   [ 0.5650157   0.5242115   0.05256954]
   [ 0.4980117   0.39909396  0.0487996 ]
   [-0.02521582  0.9589074   0.02314338]
   [ 0.795473    0.2637145   0.01227689]
   [ 0.7508882   0.71455014  0.01308271]
   [ 0.7308784   0.2789062   0.10625148]
   [ 0.50460047  0.4997428   0.02412599]
   [ 0.66110224  0.449288    0.0064396 ]]]]
[[[[0.5600253  0.47316727 0.68372434]
   [0.5086219  0.5208793  0.84531987]
   [0.5023382  0.43506873 0.727652  ]
   [0.543474   0.57563794 0.54841286]
   [0.53254944 0.38893577 0.4533762 ]
   [0.72777146 0.706902   0.7172071 ]
   [0.7182509  0.27869433 0.8069587 ]
   [0.5103763  0.5976601  0.051810

[[[[0.5559263  0.48729235 0.67161024]
   [0.51350856 0.5402403  0.72107524]
   [0.49578342 0.4555824  0.720309  ]
   [0.5557628  0.59649885 0.67992723]
   [0.5164101  0.41291273 0.5857868 ]
   [0.73423636 0.70494324 0.8453002 ]
   [0.7133459  0.27577916 0.8551313 ]
   [0.5193299  0.61240965 0.0348976 ]
   [0.49600896 0.41440466 0.0403119 ]
   [0.72810477 0.6800146  0.01356319]
   [0.48720676 0.4122337  0.06591603]
   [0.9155055  0.987892   0.00743306]
   [0.79466426 0.26176694 0.00961134]
   [0.7519646  0.717629   0.01490334]
   [0.72497606 0.27552938 0.04162419]
   [0.6635154  0.61648446 0.00405291]
   [0.47918516 0.4071767  0.02552429]]]]
[[[[0.5540112  0.51693803 0.64188087]
   [0.52073354 0.56826913 0.78495306]
   [0.49631748 0.48899385 0.7305227 ]
   [0.5671183  0.6078311  0.59350157]
   [0.5070786  0.43533894 0.72778857]
   [0.74044377 0.7110491  0.6929384 ]
   [0.70978826 0.27482313 0.62738985]
   [0.7575786  0.7469659  0.01297098]
   [0.4710964  0.42375997 0.05850095]
   [0.727

[[[[0.5698173  0.63238674 0.5910757 ]
   [0.56543875 0.6803599  0.7211237 ]
   [0.51190835 0.6123374  0.49840546]
   [0.61094195 0.689626   0.61709845]
   [0.5022037  0.52752715 0.63105226]
   [0.7490788  0.7211144  0.7185371 ]
   [0.67535174 0.2720192  0.48649383]
   [0.76892924 0.7554195  0.06652623]
   [0.6459851  0.23165661 0.00743583]
   [0.7609477  0.7535843  0.03896227]
   [0.66604716 0.3185556  0.01542816]
   [0.7709514  0.01608543 0.01845333]
   [0.762544   0.14358535 0.02085879]
   [0.7716626  0.7383296  0.07045677]
   [0.68646747 0.31923088 0.01040363]
   [0.5781022  0.6658864  0.02121389]
   [0.7626327  0.02828663 0.01684877]]]]
[[[[0.57962817 0.6385934  0.5180845 ]
   [0.57124907 0.68654734 0.67525303]
   [0.51880866 0.61787415 0.730322  ]
   [0.60751426 0.6852845  0.53255445]
   [0.5064137  0.5274524  0.7207278 ]
   [0.7486216  0.70699024 0.6958664 ]
   [0.5939762  0.30143583 0.5046709 ]
   [0.7715857  0.74523103 0.05661249]
   [0.6308857  0.20421608 0.06326184]
   [0.761

[[[[0.5550784  0.6016266  0.67809606]
   [0.53483546 0.6490641  0.8264567 ]
   [0.4978438  0.5731424  0.6990502 ]
   [0.5867318  0.6675612  0.7797619 ]
   [0.51052934 0.50372314 0.6505809 ]
   [0.74259955 0.72077686 0.6841738 ]
   [0.6938048  0.3250556  0.711602  ]
   [0.76718086 0.75896394 0.05714625]
   [0.7585403  0.27198866 0.0062106 ]
   [0.76206744 0.75815    0.02867371]
   [0.7125111  0.38309637 0.01520509]
   [0.8669444  0.7116271  0.00517282]
   [0.7940315  0.27516806 0.00641268]
   [0.76617134 0.73940206 0.05003336]
   [0.69936687 0.32816625 0.0461565 ]
   [0.55690986 0.63679314 0.02338859]
   [0.65590435 0.48163554 0.00462037]]]]
[[[[0.5558675  0.5981722  0.6666763 ]
   [0.5361311  0.6480794  0.85088384]
   [0.5000521  0.5695996  0.7794531 ]
   [0.5868497  0.6695198  0.7367779 ]
   [0.51131725 0.5011821  0.5955207 ]
   [0.7457005  0.71900284 0.6526842 ]
   [0.6922599  0.32332018 0.71881354]
   [0.77038544 0.7599047  0.04739615]
   [0.47775787 0.50723624 0.03807208]
   [0.762

[[[[0.55476594 0.5988783  0.6696189 ]
   [0.5341362  0.64737296 0.7920753 ]
   [0.49876854 0.56707615 0.70399845]
   [0.5872443  0.6658707  0.78419995]
   [0.5223263  0.4954538  0.7763517 ]
   [0.7444563  0.72145593 0.7030109 ]
   [0.69186366 0.32308677 0.7285094 ]
   [0.76584876 0.758489   0.04550844]
   [0.77543646 0.25561118 0.00799069]
   [0.7609834  0.75734    0.02583161]
   [0.73024225 0.3394218  0.00567925]
   [0.86647666 0.71159655 0.00415969]
   [0.8031157  0.26775712 0.00628692]
   [0.7667366  0.7373041  0.0489538 ]
   [0.69909835 0.32514292 0.045488  ]
   [0.5561825  0.646759   0.01997307]
   [0.4824329  0.49954548 0.00464293]]]]
[[[[0.5559493  0.5981945  0.6485435 ]
   [0.53620523 0.6459783  0.83469   ]
   [0.5012757  0.56581116 0.7461508 ]
   [0.58615535 0.6627265  0.75898814]
   [0.5193135  0.49358112 0.7133381 ]
   [0.741141   0.71780086 0.80882233]
   [0.69252026 0.3220153  0.75521046]
   [0.7666532  0.7592527  0.0523667 ]
   [0.7736673  0.25212947 0.00826761]
   [0.766

[[[[0.59959495 0.63969547 0.5517091 ]
   [0.59083825 0.6814782  0.73765016]
   [0.53481954 0.619825   0.7014377 ]
   [0.6202096  0.6738977  0.6357187 ]
   [0.5093726  0.5254403  0.64825225]
   [0.73839664 0.7034656  0.8004727 ]
   [0.6848721  0.30760503 0.7927606 ]
   [0.76450044 0.745071   0.03972858]
   [0.68245715 0.28244326 0.01072407]
   [0.74685836 0.736091   0.02610448]
   [0.7543583  0.26983818 0.00687045]
   [0.77466536 0.2554065  0.00773138]
   [0.7540026  0.24811827 0.0269742 ]
   [0.76306117 0.72533375 0.05349523]
   [0.69105947 0.3059918  0.03961411]
   [0.71253186 0.7047652  0.00771955]
   [0.6726562  0.42633232 0.00364548]]]]
[[[[0.592544   0.63953763 0.5086739 ]
   [0.5884328  0.68233544 0.73340386]
   [0.52988064 0.6210625  0.5765661 ]
   [0.62153953 0.6777472  0.6188333 ]
   [0.5060498  0.5294662  0.66302514]
   [0.7384869  0.70319915 0.7944592 ]
   [0.68418354 0.30787042 0.7283968 ]
   [0.7682339  0.74599797 0.03450042]
   [0.682912   0.28233683 0.0106006 ]
   [0.759

[[[[0.59371686 0.64816636 0.54342604]
   [0.58597475 0.68914443 0.6214675 ]
   [0.5325562  0.6280638  0.57971656]
   [0.61285424 0.6830591  0.5394935 ]
   [0.5056267  0.53754795 0.66897684]
   [0.7493164  0.7186023  0.7519549 ]
   [0.68633425 0.31579313 0.8463253 ]
   [0.77411366 0.75921977 0.0476537 ]
   [0.6817153  0.28280285 0.00910825]
   [0.7591186  0.75409806 0.03239849]
   [0.51310796 0.5326113  0.08794585]
   [0.79365706 0.25907782 0.00324196]
   [0.78478163 0.2444114  0.01029879]
   [0.77232164 0.7398254  0.04161152]
   [0.69326043 0.31568524 0.04120103]
   [0.71933126 0.7197064  0.00525153]
   [0.675656   0.46296942 0.00403166]]]]
[[[[0.58461887 0.64143336 0.43990073]
   [0.5813923  0.6860281  0.5973436 ]
   [0.52521914 0.6222897  0.6502515 ]
   [0.6184107  0.68339664 0.6859704 ]
   [0.5059446  0.53439796 0.58275294]
   [0.74197906 0.7073532  0.7561997 ]
   [0.68686575 0.31988198 0.82142353]
   [0.7701004  0.75928974 0.05623448]
   [0.6936355  0.28963554 0.00764668]
   [0.758

[[[[ 5.8665323e-01  6.3872337e-01  5.8982140e-01]
   [ 5.7652116e-01  6.8114626e-01  6.9659752e-01]
   [ 5.2383572e-01  6.1505556e-01  7.2820008e-01]
   [ 6.1148590e-01  6.7907864e-01  6.9439685e-01]
   [ 5.0999558e-01  5.2650905e-01  6.9001061e-01]
   [ 7.3936850e-01  7.0351183e-01  8.0837399e-01]
   [ 6.8756413e-01  3.1675962e-01  7.7777004e-01]
   [ 7.7184737e-01  7.5736624e-01  4.1641861e-02]
   [ 6.9429624e-01  2.8779972e-01  6.8973899e-03]
   [ 7.6279104e-01  7.5403887e-01  2.3794919e-02]
   [ 5.1834309e-01  5.2199656e-01  7.3990345e-02]
   [ 7.4502993e-01 -4.2312965e-04  6.0182810e-03]
   [ 7.8640836e-01  2.4759330e-01  8.3087385e-03]
   [ 7.6465195e-01  7.2532552e-01  4.7471374e-02]
   [ 6.9358820e-01  3.1787249e-01  4.2531073e-02]
   [ 5.9205139e-01  6.6283119e-01  2.1920532e-02]
   [ 6.7628449e-01  4.6359068e-01  6.0615540e-03]]]]
[[[[0.5861731  0.637495   0.6408682 ]
   [0.57640845 0.6806051  0.7018362 ]
   [0.52430063 0.61510396 0.71976423]
   [0.6117312  0.68006456 0.71399

[[[[0.58964694 0.6374271  0.60016495]
   [0.5799442  0.6803806  0.60912395]
   [0.52583474 0.6150496  0.67885876]
   [0.61071265 0.68143404 0.69273466]
   [0.51013726 0.526564   0.6877987 ]
   [0.738298   0.70467013 0.7897997 ]
   [0.68925375 0.31488392 0.7459325 ]
   [0.7691907  0.74764466 0.04652849]
   [0.69320095 0.28756964 0.00932738]
   [0.76495665 0.7526621  0.02996582]
   [0.51742804 0.5212612  0.07372439]
   [0.78892636 0.24598321 0.00323427]
   [0.7847902  0.24590841 0.00887039]
   [0.76483315 0.72553015 0.04769579]
   [0.6942814  0.31657952 0.04162082]
   [0.59227765 0.66248083 0.02516177]
   [0.67456716 0.4630169  0.00637633]]]]
[[[[0.58868086 0.6361036  0.6006315 ]
   [0.57948625 0.6782451  0.6270212 ]
   [0.52561903 0.61394614 0.6135695 ]
   [0.6109656  0.68010205 0.6814865 ]
   [0.50925094 0.52828634 0.66297853]
   [0.73962295 0.702803   0.80921876]
   [0.69084346 0.3133646  0.74075115]
   [0.7727504  0.75833386 0.04885113]
   [0.68523496 0.28320754 0.00662112]
   [0.764

[[[[0.5854294  0.63635147 0.59614325]
   [0.5762459  0.67897314 0.6526721 ]
   [0.52356946 0.61395913 0.63720703]
   [0.6097451  0.675654   0.5960294 ]
   [0.5052392  0.5255475  0.62502974]
   [0.74333954 0.7054676  0.7971165 ]
   [0.6864004  0.3092956  0.7999306 ]
   [0.77437294 0.7593536  0.03975487]
   [0.6866802  0.28389302 0.00692129]
   [0.762702   0.75326043 0.0232875 ]
   [0.7094182  0.35855138 0.02086833]
   [0.7901702  0.2479148  0.00324997]
   [0.7855043  0.24636464 0.00883931]
   [0.7714672  0.73460704 0.02663219]
   [0.6944269  0.31129193 0.03482476]
   [0.58705544 0.6487682  0.02466938]
   [0.6782018  0.4629421  0.00503653]]]]
[[[[0.5879004  0.6334625  0.59755987]
   [0.57669896 0.67725575 0.6445084 ]
   [0.52513343 0.6116458  0.56696403]
   [0.60863286 0.67707133 0.6004661 ]
   [0.5066872  0.52656126 0.6645365 ]
   [0.7426259  0.70645136 0.7868547 ]
   [0.6855487  0.30968562 0.82429475]
   [0.7727556  0.7481769  0.03878847]
   [0.68559104 0.28415614 0.00879923]
   [0.764

[[[[ 0.5875379   0.6299773   0.5892604 ]
   [ 0.5763063   0.6722657   0.5600982 ]
   [ 0.52367246  0.6066004   0.7343599 ]
   [ 0.6105302   0.67044175  0.5343936 ]
   [ 0.50809884  0.5213897   0.6297078 ]
   [ 0.7425695   0.70326656  0.79852045]
   [ 0.6871232   0.3061044   0.75781894]
   [ 0.76992404  0.7470964   0.04131895]
   [ 0.6884461   0.282362    0.00744924]
   [ 0.76263374  0.7508612   0.02411866]
   [ 0.7191915   0.35416192  0.01350388]
   [ 0.7476229  -0.00452195  0.00561059]
   [ 0.78763354  0.24707875  0.00834882]
   [ 0.76570636  0.7249117   0.02811944]
   [ 0.6940333   0.30771714  0.03210011]
   [ 0.5852339   0.6466826   0.03540725]
   [ 0.6817034   0.45505795  0.00563598]]]]
[[[[0.5902812  0.63054115 0.57003355]
   [0.5769879  0.6738324  0.57479924]
   [0.52469176 0.60710686 0.7086927 ]
   [0.6102646  0.67131066 0.5262057 ]
   [0.507046   0.5199295  0.61261785]
   [0.740241   0.70032465 0.8200238 ]
   [0.686012   0.3079779  0.8140142 ]
   [0.7708019  0.7479049  0.054880

[[[[0.58849233 0.62568647 0.52910286]
   [0.5756673  0.67028135 0.6687102 ]
   [0.5237287  0.60524124 0.7403422 ]
   [0.6080121  0.671622   0.51928216]
   [0.50658095 0.51953197 0.5806512 ]
   [0.73848283 0.70244426 0.8028376 ]
   [0.68798965 0.30670086 0.7437163 ]
   [0.7687113  0.747695   0.04081759]
   [0.68732464 0.28373137 0.00650966]
   [0.76167077 0.75120795 0.02254981]
   [0.70905876 0.37219375 0.01822454]
   [0.74706024 0.00219176 0.0068793 ]
   [0.7749318  0.25194082 0.01024455]
   [0.7621922  0.72383446 0.03147998]
   [0.6946003  0.3075469  0.03441399]
   [0.58560073 0.6472952  0.03961924]
   [0.68106705 0.4543029  0.00580662]]]]
[[[[0.58952105 0.6239595  0.5871205 ]
   [0.57460135 0.66961324 0.6967702 ]
   [0.5236395  0.6043732  0.7566091 ]
   [0.6053714  0.6741767  0.6321276 ]
   [0.504891   0.5202747  0.5706635 ]
   [0.7369211  0.702055   0.7856018 ]
   [0.6887282  0.3082446  0.7469298 ]
   [0.76481026 0.747005   0.03795579]
   [0.68410766 0.28405917 0.00776893]
   [0.750

[[[[0.58768356 0.6253674  0.5591355 ]
   [0.5733071  0.6682086  0.7311607 ]
   [0.5203413  0.6019554  0.7706066 ]
   [0.60515344 0.6664131  0.5481334 ]
   [0.5014652  0.5126441  0.54024476]
   [0.73868686 0.70217407 0.822829  ]
   [0.69439083 0.29840142 0.859302  ]
   [0.76869446 0.7470431  0.04078189]
   [0.49362618 0.5185033  0.02432355]
   [0.7623173  0.75135785 0.01940468]
   [0.709416   0.34375724 0.01417384]
   [0.7617663  0.00337258 0.00712758]
   [0.7897158  0.23900835 0.00686997]
   [0.7648515  0.72287124 0.04168695]
   [0.702568   0.297857   0.02728888]
   [0.58268327 0.6526887  0.0303798 ]
   [0.6821578  0.45412037 0.00637034]]]]
[[[[0.58901703 0.6230532  0.6179032 ]
   [0.5742549  0.6663363  0.7273464 ]
   [0.52088237 0.6003888  0.7620821 ]
   [0.606174   0.6671339  0.5528537 ]
   [0.50096273 0.51324785 0.58275735]
   [0.73787373 0.7009129  0.81005394]
   [0.69263846 0.29848635 0.839787  ]
   [0.7694615  0.7483723  0.04214397]
   [0.49333084 0.51954895 0.02255976]
   [0.751

[[[[0.57422495 0.5989322  0.62359667]
   [0.5537641  0.6458894  0.8025863 ]
   [0.51292133 0.5710872  0.5840458 ]
   [0.5956348  0.6557163  0.59628576]
   [0.51225954 0.4920761  0.6382579 ]
   [0.73624396 0.70090216 0.7792586 ]
   [0.69221956 0.3057597  0.691042  ]
   [0.76710993 0.7574426  0.05885285]
   [0.696579   0.2893319  0.0072875 ]
   [0.7595784  0.7586657  0.03409106]
   [0.721256   0.31928873 0.00848991]
   [0.9079004  0.99204946 0.0104318 ]
   [0.7877811  0.25440812 0.00997788]
   [0.7603269  0.7244098  0.03930369]
   [0.69624174 0.3045713  0.07334316]
   [0.56140375 0.633735   0.03544977]
   [0.6606941  0.4728     0.00746936]]]]
[[[[0.5766501  0.60171187 0.5037607 ]
   [0.55228263 0.64513886 0.82266486]
   [0.5144901  0.57029486 0.6765624 ]
   [0.59446704 0.65571886 0.6527547 ]
   [0.51731604 0.48708954 0.48238176]
   [0.731157   0.6965186  0.795614  ]
   [0.6922962  0.30481374 0.65820587]
   [0.7680232  0.7575349  0.05751213]
   [0.5111771  0.49284935 0.02427107]
   [0.762

[[[[0.5678226  0.5974469  0.63553846]
   [0.5452049  0.6433942  0.54103744]
   [0.5060328  0.5671885  0.7859118 ]
   [0.5913814  0.6538794  0.64773214]
   [0.51478815 0.48696837 0.44604728]
   [0.7423612  0.70150656 0.8380718 ]
   [0.6938767  0.30367732 0.84059674]
   [0.76856333 0.74622005 0.03997269]
   [0.49216166 0.49451283 0.03474164]
   [0.7637324  0.752016   0.02783239]
   [0.7256908  0.35482937 0.01354495]
   [0.9151048  0.9817052  0.01369506]
   [0.78968275 0.25345796 0.00973609]
   [0.76319516 0.72341406 0.05376869]
   [0.7005732  0.30170378 0.05586803]
   [0.5406743  0.62219536 0.03322822]
   [0.69561136 0.45641777 0.00796497]]]]
[[[[0.56681806 0.59806883 0.5945704 ]
   [0.5453581  0.6431845  0.54778475]
   [0.5058434  0.5668702  0.78018415]
   [0.5898709  0.65286255 0.6474416 ]
   [0.513825   0.48606068 0.43035144]
   [0.7419123  0.7017384  0.8321802 ]
   [0.6963432  0.29936892 0.86566055]
   [0.76898307 0.7470425  0.03676683]
   [0.4922274  0.4942406  0.03212216]
   [0.763

[[[[0.51963836 0.52658474 0.7403169 ]
   [0.48623654 0.56896555 0.74946827]
   [0.48702815 0.49054664 0.84020054]
   [0.54046637 0.624015   0.678786  ]
   [0.5319743  0.4483232  0.55921924]
   [0.7403053  0.7437156  0.78734386]
   [0.7169804  0.3140498  0.85559887]
   [0.7653824  0.90206146 0.01711833]
   [0.77181345 0.26145318 0.00709474]
   [0.7222426  0.7491043  0.01191157]
   [0.7303486  0.28072405 0.01044878]
   [0.8613863  0.7092792  0.00184914]
   [0.80790156 0.2908057  0.00957569]
   [0.61590314 0.72361344 0.00226113]
   [0.7303338  0.31101242 0.10926419]
   [0.47765774 0.55161697 0.02940968]
   [0.48086482 0.47193623 0.01828936]]]]
[[[[0.5192877  0.5229976  0.7580297 ]
   [0.4887472  0.56511253 0.7920611 ]
   [0.48616633 0.48729888 0.77539074]
   [0.54871005 0.61947453 0.68672824]
   [0.53309125 0.43845776 0.5348701 ]
   [0.7515758  0.7464466  0.86244905]
   [0.7351697  0.3004326  0.8852806 ]
   [0.7565351  0.7741533  0.00957397]
   [0.7738706  0.26059446 0.00763243]
   [0.727

[[[[0.70210594 0.55188555 0.58334464]
   [0.63952875 0.5996478  0.53055733]
   [0.63261646 0.5062632  0.7127722 ]
   [0.6155849  0.6453642  0.6902265 ]
   [0.5937106  0.44064373 0.6362795 ]
   [0.77522635 0.74417156 0.71503925]
   [0.7497593  0.30449432 0.7207284 ]
   [0.77361864 0.7607963  0.04079774]
   [0.7726906  0.2795805  0.01158643]
   [0.7551729  0.7519986  0.05071434]
   [0.698387   0.48942456 0.03532779]
   [0.53495085 0.492417   0.05495423]
   [0.80557007 0.2868839  0.02342251]
   [0.77862865 0.7518389  0.03083152]
   [0.7607802  0.3043636  0.0991461 ]
   [0.68889827 0.58516    0.03278321]
   [0.69631255 0.48677748 0.01336858]]]]
[[[[0.7031847  0.5524166  0.61808956]
   [0.64005935 0.5987262  0.59963286]
   [0.63588554 0.5062046  0.7939228 ]
   [0.6121745  0.6457196  0.7036592 ]
   [0.59454507 0.4401012  0.6384402 ]
   [0.773965   0.74777794 0.56874204]
   [0.7513971  0.30590525 0.67678595]
   [0.7740904  0.7604548  0.04464012]
   [0.771186   0.2885814  0.0143941 ]
   [0.755

[[[[0.7666787  0.5370299  0.60122895]
   [0.7235089  0.57917535 0.6580848 ]
   [0.717191   0.496739   0.7453043 ]
   [0.64168674 0.6423795  0.62702453]
   [0.6316043  0.42543793 0.636183  ]
   [0.771274   0.7349262  0.5937904 ]
   [0.75130063 0.30789304 0.5113627 ]
   [0.7739556  0.76360255 0.03590864]
   [0.7752509  0.28720763 0.03179961]
   [0.6006095  0.67163664 0.0627591 ]
   [0.74147975 0.2846343  0.02641058]
   [0.66377825 0.6685297  0.0487228 ]
   [0.7860479  0.29363567 0.06535625]
   [0.72131383 0.57697076 0.03356412]
   [0.7611022  0.29975772 0.10466164]
   [0.7192652  0.5746129  0.04251909]
   [0.75247276 0.28105897 0.01158282]]]]
[[[[0.76448345 0.5370546  0.5814265 ]
   [0.72082347 0.580418   0.5819956 ]
   [0.714236   0.49600628 0.75081164]
   [0.64329535 0.6399927  0.628989  ]
   [0.6218662  0.42425242 0.4224128 ]
   [0.77041274 0.73777956 0.63863707]
   [0.7492375  0.30765042 0.49423078]
   [0.77396166 0.7612112  0.03436726]
   [0.7740867  0.28751352 0.02556628]
   [0.753

[[[[0.75496507 0.5370429  0.6265175 ]
   [0.7058603  0.5815141  0.6784224 ]
   [0.69687605 0.49658522 0.6780087 ]
   [0.63044536 0.6503474  0.77735424]
   [0.6113215  0.42847675 0.6072317 ]
   [0.7730732  0.73210466 0.5357291 ]
   [0.74734026 0.31115264 0.50891536]
   [0.7717443  0.75809085 0.04512262]
   [0.7723168  0.2905534  0.07602179]
   [0.7531706  0.75311214 0.03957945]
   [0.7656844  0.26471582 0.04674619]
   [0.62641627 0.447279   0.06994104]
   [0.7933669  0.2971061  0.03442606]
   [0.72236073 0.5863524  0.03427017]
   [0.75727093 0.30149725 0.06746897]
   [0.71015584 0.57417065 0.05129585]
   [0.75608814 0.27981174 0.01593226]]]]
[[[[0.7564656  0.53852576 0.6274656 ]
   [0.7060167  0.58310974 0.6992378 ]
   [0.69630134 0.49674052 0.70242804]
   [0.6329463  0.64991665 0.7523931 ]
   [0.6166669  0.42874444 0.6428876 ]
   [0.775111   0.73664665 0.52969575]
   [0.7451599  0.3146671  0.49363935]
   [0.7730035  0.76031995 0.05578661]
   [0.77199817 0.29118103 0.06622687]
   [0.753

[[[[0.5770712  0.5408781  0.60732144]
   [0.5376603  0.5832543  0.8510909 ]
   [0.5294299  0.50579506 0.62850785]
   [0.5732716  0.62950414 0.7791226 ]
   [0.5568479  0.45507592 0.6221219 ]
   [0.7655494  0.73805714 0.7387172 ]
   [0.74237543 0.31700084 0.77783656]
   [0.7733136  0.7739232  0.02260488]
   [0.7747088  0.27700898 0.006338  ]
   [0.7519265  0.731333   0.0196788 ]
   [0.5574854  0.458043   0.02835754]
   [0.8553353  0.7052817  0.00280583]
   [0.8120024  0.29898587 0.00881025]
   [0.77494234 0.75528055 0.03552589]
   [0.7499863  0.31303623 0.11636549]
   [0.66339254 0.65590173 0.00746801]
   [0.5122412  0.4519174  0.01476517]]]]
[[[[0.5787885  0.53772247 0.60789084]
   [0.53661186 0.58200556 0.812278  ]
   [0.52923614 0.50330275 0.60098267]
   [0.57110095 0.6273915  0.7129912 ]
   [0.5536265  0.4541992  0.59094393]
   [0.76781094 0.73754466 0.7104754 ]
   [0.73779887 0.3198147  0.8621823 ]
   [0.7715813  0.7647057  0.01557848]
   [0.7730426  0.27632588 0.0060806 ]
   [0.749

[[[[0.57770807 0.56091946 0.48300594]
   [0.54029703 0.61167294 0.8301654 ]
   [0.5190741  0.52508104 0.78740543]
   [0.58194846 0.6510521  0.5848626 ]
   [0.5403314  0.47024786 0.56546044]
   [0.76745415 0.7419735  0.7651879 ]
   [0.7178649  0.31244922 0.8965468 ]
   [0.7723114  0.7782313  0.02354079]
   [0.76928914 0.26224214 0.00825444]
   [0.7576065  0.76645046 0.03057012]
   [0.71559244 0.28878638 0.03321481]
   [0.87362397 0.7161794  0.00382614]
   [0.8025018  0.28997743 0.00836825]
   [0.7771316  0.75527346 0.03076452]
   [0.7234521  0.31321746 0.10937309]
   [0.56470084 0.6064089  0.02863851]
   [0.49820036 0.46881735 0.01605394]]]]
[[[[0.5815549  0.5653258  0.66178256]
   [0.54333496 0.6129892  0.7752136 ]
   [0.5220463  0.527505   0.7591653 ]
   [0.5807201  0.6522386  0.5866128 ]
   [0.5422411  0.47147495 0.5630689 ]
   [0.76284397 0.73854214 0.6599718 ]
   [0.7164049  0.31379327 0.88893414]
   [0.7699308  0.7804233  0.02719009]
   [0.76688844 0.2744964  0.0060803 ]
   [0.756

[[[[0.58647895 0.5848845  0.7252244 ]
   [0.55202305 0.6347834  0.7018375 ]
   [0.5222949  0.55292404 0.8415718 ]
   [0.5947812  0.65783894 0.6607593 ]
   [0.5363548  0.48045614 0.77292585]
   [0.7668257  0.7364693  0.68200594]
   [0.71798825 0.31908995 0.8645607 ]
   [0.77487344 0.77617353 0.03457665]
   [0.7334186  0.30625227 0.00987959]
   [0.7588693  0.7691533  0.02907696]
   [0.7240253  0.30186594 0.01454997]
   [0.8564696  0.6985037  0.00677219]
   [0.80122924 0.2914704  0.0082638 ]
   [0.77979815 0.7562869  0.04474899]
   [0.7257508  0.3171356  0.1480828 ]
   [0.5708964  0.6321116  0.02949587]
   [0.6722861  0.489542   0.00681254]]]]
[[[[0.58561194 0.5849917  0.71767473]
   [0.5504012  0.6344535  0.66175187]
   [0.5215398  0.5519054  0.8367238 ]
   [0.59072244 0.6592612  0.6385085 ]
   [0.5351608  0.4812366  0.75729537]
   [0.76677763 0.7393572  0.684109  ]
   [0.71825916 0.31638864 0.8962513 ]
   [0.77383155 0.7776859  0.03149831]
   [0.49309158 0.48211193 0.03276369]
   [0.759

[[[[0.5807303  0.5915109  0.6125352 ]
   [0.54719263 0.64160335 0.56395197]
   [0.518869   0.55797243 0.810474  ]
   [0.5897638  0.6671513  0.6207067 ]
   [0.5324046  0.49074832 0.6273316 ]
   [0.767694   0.7374579  0.64628303]
   [0.71969867 0.32105088 0.8342531 ]
   [0.77767915 0.7943716  0.02740017]
   [0.76069343 0.26670122 0.00458485]
   [0.7588269  0.78692347 0.03082672]
   [0.72893244 0.33147645 0.00792506]
   [0.85229427 0.68670684 0.00662133]
   [0.8071071  0.27602223 0.00694406]
   [0.78181463 0.75900686 0.03745762]
   [0.7272961  0.3165929  0.09231839]
   [0.56666    0.63599414 0.02876776]
   [0.67490876 0.4868096  0.00630668]]]]
[[[[0.579222   0.5909265  0.5965887 ]
   [0.547702   0.640486   0.5668782 ]
   [0.519151   0.5580956  0.787444  ]
   [0.59075916 0.66594577 0.6760726 ]
   [0.533366   0.48970914 0.62995046]
   [0.7664366  0.7384996  0.7005492 ]
   [0.71490926 0.3198785  0.8144959 ]
   [0.7748122  0.7793168  0.02353749]
   [0.49674684 0.49877378 0.03231168]
   [0.764

[[[[0.5845879  0.5937012  0.57442683]
   [0.5518045  0.6466728  0.83068585]
   [0.52109057 0.5639034  0.70625883]
   [0.5973348  0.6706732  0.6487262 ]
   [0.52903914 0.49391708 0.6032    ]
   [0.76892805 0.7395118  0.70583934]
   [0.71632004 0.3192035  0.82181865]
   [0.7750211  0.77861685 0.028588  ]
   [0.7342837  0.31264776 0.00930935]
   [0.76000565 0.7842319  0.03347862]
   [0.7162219  0.33617178 0.01629236]
   [0.85512215 0.69949305 0.00503078]
   [0.81040746 0.27605063 0.00532514]
   [0.782474   0.75836444 0.03163224]
   [0.72458726 0.3212765  0.05963999]
   [0.5701736  0.6389579  0.03625247]
   [0.5004846  0.49780267 0.01101804]]]]
[[[[0.5861717  0.59749085 0.67967284]
   [0.5492308  0.64803755 0.78248364]
   [0.5220876  0.56508464 0.76667035]
   [0.5922969  0.6705755  0.59122586]
   [0.5347081  0.49442345 0.7183627 ]
   [0.7689333  0.73974884 0.7153934 ]
   [0.7201666  0.31880876 0.88048464]
   [0.77618957 0.7752528  0.02094826]
   [0.4933618  0.49699217 0.03190878]
   [0.760

[[[[0.6120141  0.38545164 0.6077315 ]
   [0.5410094  0.4228314  0.65719354]
   [0.57607967 0.3412813  0.6094034 ]
   [0.5314242  0.5143675  0.6224588 ]
   [0.5929956  0.35534027 0.4377308 ]
   [0.7493433  0.719833   0.817976  ]
   [0.75817263 0.28327307 0.8514712 ]
   [0.75765514 0.74439275 0.0047164 ]
   [0.7719897  0.23367909 0.00702694]
   [0.5262975  0.5038849  0.02238646]
   [0.66170573 0.2706222  0.02135098]
   [0.8948561  0.9909356  0.00468251]
   [0.9141201  0.8958714  0.00689957]
   [0.76328003 0.7371115  0.01206392]
   [0.766789   0.28240457 0.10417008]
   [0.6921159  0.44311506 0.0012112 ]
   [0.56659174 0.31785643 0.01658297]]]]
[[[[0.6263546  0.35262445 0.5956223 ]
   [0.5548427  0.38289806 0.7372932 ]
   [0.5992383  0.30948442 0.73338383]
   [0.5281782  0.478107   0.531939  ]
   [0.60363305 0.32748014 0.56110716]
   [0.7454463  0.7085808  0.8039036 ]
   [0.77095175 0.27960595 0.6731832 ]
   [0.7575468  0.7481543  0.00490355]
   [0.7740367  0.19589634 0.01699388]
   [0.533

[[[[0.6532796  0.3054987  0.5471534 ]
   [0.5808835  0.32772207 0.57466227]
   [0.6313306  0.2624208  0.6932642 ]
   [0.5408637  0.43339822 0.52779955]
   [0.644805   0.2746002  0.4735092 ]
   [0.72492146 0.68866754 0.7541872 ]
   [0.7780874  0.2875293  0.39219785]
   [0.7416403  0.722254   0.00584504]
   [0.77575344 0.1874541  0.0342938 ]
   [0.5902067  0.4729878  0.0029231 ]
   [0.7666188  0.18722746 0.03004551]
   [0.91330254 0.9905787  0.01206487]
   [0.8094408  0.7422627  0.01015493]
   [0.7499402  0.7101393  0.00864729]
   [0.7919908  0.2767516  0.09482318]
   [0.76999575 0.21633953 0.00974292]
   [0.7642251  0.27737933 0.01511356]]]]
[[[[0.6540195  0.31170127 0.6241666 ]
   [0.58155376 0.33335432 0.6851077 ]
   [0.6331516  0.26690963 0.56949055]
   [0.54023504 0.43767932 0.6467182 ]
   [0.64659786 0.27784613 0.42754334]
   [0.72504085 0.6868052  0.7917452 ]
   [0.777435   0.2812919  0.4301996 ]
   [0.74091136 0.72295535 0.00434297]
   [0.77619    0.19027174 0.02508381]
   [0.549

[[[[0.6345057  0.3279548  0.5080133 ]
   [0.56390196 0.35841477 0.43321663]
   [0.60886544 0.28808913 0.62932605]
   [0.53216535 0.46093667 0.6131434 ]
   [0.61437565 0.30165547 0.54520524]
   [0.7365837  0.70276827 0.7350044 ]
   [0.77355456 0.28351083 0.68969345]
   [0.74956465 0.7354999  0.00543374]
   [0.7761413  0.20289038 0.02553794]
   [0.53127384 0.46087548 0.02162102]
   [0.76232517 0.21196973 0.03141388]
   [0.88912666 0.9902618  0.01091695]
   [0.81360453 0.75526464 0.00679955]
   [0.75625515 0.7209641  0.00640562]
   [0.78627515 0.28408408 0.07086769]
   [0.7482512  0.48432446 0.00355005]
   [0.6031988  0.27219626 0.02450615]]]]
[[[[0.6384278  0.3349284  0.48388913]
   [0.56645125 0.3616628  0.6008854 ]
   [0.61330235 0.28909507 0.79242456]
   [0.52861536 0.46360195 0.62882656]
   [0.6271709  0.29973575 0.5007421 ]
   [0.73838127 0.69804215 0.657714  ]
   [0.7787171  0.28682637 0.59551305]
   [0.7470579  0.7280192  0.00559828]
   [0.7748514  0.19223632 0.02517512]
   [0.525

[[[[0.6302565  0.3592814  0.49671948]
   [0.55976766 0.39038345 0.5743792 ]
   [0.6041417  0.3135918  0.61015904]
   [0.532048   0.48441848 0.6217153 ]
   [0.61752975 0.3210784  0.56766415]
   [0.74408174 0.71814847 0.798249  ]
   [0.77688855 0.28707162 0.7085656 ]
   [0.75450027 0.7411809  0.00417396]
   [0.7762326  0.20495984 0.01310137]
   [0.52366555 0.48253512 0.00969127]
   [0.7598592  0.19591433 0.02485549]
   [0.86556166 0.95372564 0.00893742]
   [0.8143513  0.7515491  0.00631055]
   [0.75979453 0.7340586  0.00723833]
   [0.7861534  0.2877056  0.09061944]
   [0.7650055  0.28474218 0.00707859]
   [0.5798232  0.29662985 0.03071016]]]]
[[[[0.630176   0.36072147 0.44183236]
   [0.5596825  0.3926373  0.62158376]
   [0.60172635 0.31473017 0.5861243 ]
   [0.53143233 0.48479566 0.6179465 ]
   [0.613795   0.32242894 0.56459886]
   [0.7440597  0.71981937 0.7542076 ]
   [0.7793538  0.282917   0.68761575]
   [0.76100695 0.7579212  0.00321651]
   [0.7762346  0.20055744 0.01843479]
   [0.523

[[[[0.6260754  0.37447304 0.5252012 ]
   [0.5552691  0.40206906 0.7243959 ]
   [0.594617   0.32383722 0.6902546 ]
   [0.5349321  0.48787713 0.699836  ]
   [0.61625767 0.32633018 0.49909937]
   [0.7428079  0.7207951  0.80093193]
   [0.77401006 0.2846932  0.80981433]
   [0.75823444 0.76116735 0.00431845]
   [0.7776562  0.22725695 0.00955048]
   [0.52625823 0.4853153  0.0136776 ]
   [0.7612748  0.19668478 0.01779416]
   [0.88219476 0.9643016  0.00635889]
   [0.8037578  0.75226396 0.00563303]
   [0.75775266 0.7382274  0.00865343]
   [0.7816129  0.28447834 0.13700631]
   [0.9804247  0.02330705 0.01348162]
   [0.5749548  0.29965973 0.04574019]]]]
[[[[0.6270953  0.3782539  0.58184886]
   [0.55688125 0.40695354 0.6498106 ]
   [0.59477043 0.3255855  0.5799111 ]
   [0.5382283  0.49130508 0.74313575]
   [0.62095714 0.32595292 0.5613369 ]
   [0.7437983  0.7185224  0.81047595]
   [0.7763045  0.2774019  0.7910266 ]
   [0.75866985 0.7586656  0.00363716]
   [0.77621144 0.205431   0.01228553]
   [0.524

[[[[0.62430376 0.38908684 0.5669392 ]
   [0.5527204  0.42560816 0.7639069 ]
   [0.58732736 0.336401   0.75334334]
   [0.5415868  0.51145136 0.52956384]
   [0.6111526  0.3365002  0.44228473]
   [0.7461036  0.7201762  0.6973685 ]
   [0.77432096 0.2843048  0.8521012 ]
   [0.7533469  0.7425865  0.00497213]
   [0.77973783 0.25742403 0.0082837 ]
   [0.5600963  0.5126851  0.01768482]
   [0.58142585 0.3141284  0.0445393 ]
   [0.86889356 0.9479323  0.00608245]
   [0.8276642  0.27936113 0.0088501 ]
   [0.7639927  0.7377523  0.0069651 ]
   [0.7833609  0.28738376 0.1302239 ]
   [0.7279566  0.5005746  0.00296253]
   [0.5584561  0.3170969  0.06282753]]]]
[[[[0.6229511  0.38906014 0.5607562 ]
   [0.5518989  0.42432967 0.7050429 ]
   [0.5868667  0.33819428 0.78098327]
   [0.5394005  0.5099343  0.7545023 ]
   [0.60908145 0.33781898 0.43292043]
   [0.7442937  0.717577   0.78462267]
   [0.7720705  0.29037037 0.84996235]
   [0.7553353  0.7541312  0.00379449]
   [0.7751398  0.2093313  0.00875801]
   [0.560

[[[[0.6220182  0.36205968 0.49426734]
   [0.5521677  0.39909035 0.8506153 ]
   [0.5903598  0.31693864 0.79596734]
   [0.53728193 0.49287537 0.74406195]
   [0.6092686  0.32986224 0.5968932 ]
   [0.74882627 0.71737033 0.84328103]
   [0.77898985 0.2747491  0.7948654 ]
   [0.7571813  0.7429119  0.00457481]
   [0.7753806  0.19381703 0.00654936]
   [0.56216383 0.51086694 0.01010031]
   [0.7606493  0.1937987  0.01563302]
   [0.88315594 0.96972626 0.00631073]
   [0.82733434 0.25614813 0.00712404]
   [0.7628724  0.7326302  0.01094276]
   [0.78841937 0.27467299 0.08543998]
   [0.49133503 0.31340966 0.01151401]
   [0.57110137 0.3119216  0.04346827]]]]
[[[[0.621144   0.3612899  0.46149313]
   [0.5519953  0.40007395 0.846575  ]
   [0.5862856  0.3147113  0.8210797 ]
   [0.53844345 0.4935961  0.7266964 ]
   [0.6060703  0.3280506  0.5841201 ]
   [0.7500907  0.71764886 0.83342934]
   [0.7807794  0.2760374  0.6976156 ]
   [0.75857663 0.75092566 0.00272274]
   [0.77679414 0.2051566  0.00840485]
   [0.562

[[[[ 0.60144305  0.4182535   0.68701255]
   [ 0.5355114   0.4618576   0.8403835 ]
   [ 0.55404407  0.3748599   0.6831818 ]
   [ 0.54650086  0.53927785  0.70038736]
   [ 0.58435154  0.35061353  0.6210777 ]
   [ 0.753595    0.72614986  0.67449445]
   [ 0.7627101   0.29159927  0.69313574]
   [ 0.7560289   0.74439335  0.00822708]
   [ 0.77661353  0.26158988  0.00583181]
   [ 0.61614156  0.4781625   0.0211522 ]
   [ 0.5419284   0.34650934  0.04019588]
   [-0.02522066  0.96597147  0.02628249]
   [ 0.8269113   0.27591127  0.00747049]
   [ 0.7610184   0.7405612   0.02833775]
   [ 0.774082    0.29296318  0.10286102]
   [ 0.7139137   0.5266035   0.0043647 ]
   [ 0.5286008   0.34613693  0.05936944]]]]
[[[[ 0.5980809   0.4271042   0.70177543]
   [ 0.5345612   0.46930155  0.6373055 ]
   [ 0.5489718   0.38440502  0.6586621 ]
   [ 0.55108917  0.5437076   0.59153384]
   [ 0.5798694   0.36102182  0.5214954 ]
   [ 0.75679904  0.73105216  0.7350174 ]
   [ 0.75969     0.28984132  0.85423255]
   [ 0.542022

[[[[0.6073905  0.6656365  0.47161743]
   [0.60526246 0.7056942  0.5296629 ]
   [0.5525977  0.6376296  0.7151236 ]
   [0.63527787 0.7008829  0.5538318 ]
   [0.5279656  0.5422443  0.6404707 ]
   [0.7694038  0.7356975  0.5433417 ]
   [0.7216019  0.29858533 0.7250526 ]
   [0.77748895 0.759961   0.00821871]
   [0.721373   0.25767812 0.01691133]
   [0.75256157 0.75377196 0.0117932 ]
   [0.714977   0.28590286 0.01967984]
   [0.52740425 0.99301374 0.0177739 ]
   [0.7896945  0.19717728 0.00766709]
   [0.6092297  0.6499773  0.00955284]
   [0.7300476  0.29523474 0.02030247]
   [0.6115524  0.68442404 0.01050878]
   [0.530944   0.89764386 0.01367182]]]]
[[[[0.6056077  0.6647049  0.45275933]
   [0.6028654  0.70491993 0.49833214]
   [0.5531367  0.63680696 0.70597726]
   [0.63194627 0.70225084 0.5463326 ]
   [0.5302785  0.54308754 0.62179995]
   [0.7657607  0.73179126 0.45646575]
   [0.7199647  0.29903775 0.65453005]
   [0.7744177  0.7595729  0.00657755]
   [0.72170144 0.2575178  0.02789876]
   [0.753

[[[[0.6019498  0.6539354  0.51391166]
   [0.59801817 0.6982166  0.6030835 ]
   [0.5486526  0.6291241  0.5546744 ]
   [0.6298993  0.6943422  0.64286435]
   [0.52332187 0.53978586 0.6409014 ]
   [0.76635903 0.73047435 0.5775745 ]
   [0.718867   0.2977586  0.7245476 ]
   [0.77420384 0.7572892  0.01095995]
   [0.6338507  0.2049487  0.00538886]
   [0.7520365  0.75189084 0.01549688]
   [0.7044213  0.27605715 0.02750325]
   [0.5084526  0.9300259  0.01496381]
   [0.7910496  0.20106187 0.00658163]
   [0.78100246 0.7446341  0.00599614]
   [0.72688174 0.29315257 0.02795973]
   [0.6010247  0.6751241  0.01491645]
   [0.5190307  0.8969293  0.02127334]]]]
[[[[0.5992136  0.65166825 0.52324253]
   [0.5987137  0.6944429  0.6307675 ]
   [0.54676306 0.6254653  0.5070414 ]
   [0.6311863  0.69303286 0.64415836]
   [0.5238633  0.5393038  0.6513608 ]
   [0.7670965  0.7232749  0.5068616 ]
   [0.71813416 0.29677525 0.679319  ]
   [0.77606523 0.7595157  0.00974688]
   [0.6462503  0.20027749 0.00378072]
   [0.764

[[[[0.6085872  0.6385419  0.47957343]
   [0.60123163 0.6849214  0.60568136]
   [0.55176026 0.61527807 0.7073355 ]
   [0.63169813 0.6889663  0.6030472 ]
   [0.5254318  0.52851635 0.6330719 ]
   [0.766928   0.7240284  0.55605215]
   [0.7191287  0.29986542 0.7439431 ]
   [0.77510303 0.7494185  0.01290935]
   [0.6478368  0.19930671 0.00300398]
   [0.7640497  0.75031507 0.01477438]
   [0.71775824 0.28077996 0.02982873]
   [0.7921529  0.93402433 0.01279452]
   [0.7922936  0.2164832  0.00542018]
   [0.78019077 0.7432829  0.00717422]
   [0.7321889  0.29903308 0.0199675 ]
   [0.6021251  0.6514971  0.0244396 ]
   [0.70779735 0.4032     0.00191236]]]]
[[[[0.6085322  0.6398488  0.4539132 ]
   [0.601307   0.68821025 0.446677  ]
   [0.5501759  0.6167468  0.6811983 ]
   [0.6334401  0.68890625 0.61982775]
   [0.52379185 0.52876955 0.65130395]
   [0.7687073  0.72050315 0.66051805]
   [0.72509134 0.29831094 0.7987366 ]
   [0.7778942  0.74837667 0.01452214]
   [0.7266729  0.2615376  0.00710335]
   [0.765

[[[[0.6018269  0.64080626 0.49654883]
   [0.595253   0.68553007 0.5414897 ]
   [0.54465294 0.6177113  0.5760105 ]
   [0.6268446  0.6856163  0.48324072]
   [0.5183441  0.5273998  0.624235  ]
   [0.7632906  0.72272563 0.6633558 ]
   [0.7233196  0.29432887 0.70186746]
   [0.7760741  0.7594423  0.01330781]
   [0.73007596 0.25880212 0.01016352]
   [0.75649345 0.7504516  0.01806608]
   [0.7173761  0.27780998 0.02696833]
   [0.7977946  0.89805615 0.01184317]
   [0.79472536 0.22166158 0.0066627 ]
   [0.77868193 0.74753505 0.00821817]
   [0.7361141  0.2909379  0.02625078]
   [0.59948826 0.660226   0.02169341]
   [0.7099308  0.40746233 0.0023194 ]]]]
[[[[0.60334504 0.64325815 0.40912947]
   [0.5954307  0.6869753  0.5094164 ]
   [0.5444957  0.6197975  0.5898963 ]
   [0.6225786  0.6842116  0.5587307 ]
   [0.5154904  0.5280264  0.6308204 ]
   [0.7627415  0.7207283  0.5887094 ]
   [0.7245509  0.2942301  0.7336893 ]
   [0.7736176  0.7565315  0.01501286]
   [0.7281651  0.2605392  0.00713253]
   [0.755

[[[[0.60501766 0.63775945 0.6056287 ]
   [0.593567   0.682235   0.59692377]
   [0.54495347 0.614042   0.49755153]
   [0.6214802  0.6828766  0.55561084]
   [0.52214897 0.52536255 0.65231013]
   [0.76118356 0.720952   0.6682778 ]
   [0.7204593  0.3005654  0.7206855 ]
   [0.77105343 0.74987596 0.01537025]
   [0.7279081  0.2606808  0.00807855]
   [0.7565647  0.75072545 0.02058604]
   [0.7229351  0.29100174 0.02330405]
   [0.7914026  0.19668503 0.00309557]
   [0.7922554  0.20537153 0.00605032]
   [0.7771235  0.74265695 0.01103103]
   [0.73241985 0.30804136 0.01879513]
   [0.5961278  0.66671467 0.02637315]
   [0.7057407  0.42127958 0.00352153]]]]
[[[[0.6037631  0.6343466  0.5936868 ]
   [0.59330004 0.68086463 0.62035924]
   [0.54415655 0.6112266  0.48450235]
   [0.62279385 0.68547094 0.58014464]
   [0.5226438  0.5245081  0.6750265 ]
   [0.76368254 0.7212432  0.66447324]
   [0.7232311  0.3006361  0.7604164 ]
   [0.7695606  0.7489068  0.01155087]
   [0.72750974 0.2622229  0.00583225]
   [0.756

[[[[0.5928703  0.62006426 0.57653123]
   [0.5825967  0.6658269  0.72815025]
   [0.5350417  0.5951632  0.60454905]
   [0.620562   0.6721182  0.6344538 ]
   [0.5246384  0.51146615 0.66925824]
   [0.7588456  0.7043752  0.6370471 ]
   [0.72924274 0.3023249  0.78574145]
   [0.775896   0.75970536 0.02335492]
   [0.72856176 0.2621967  0.00395024]
   [0.75763476 0.75499713 0.02433783]
   [0.72437596 0.30820864 0.01400387]
   [0.4209817  0.83846205 0.00919205]
   [0.797528   0.23934305 0.00533372]
   [0.77865225 0.7387089  0.01616952]
   [0.73628104 0.30374706 0.02563557]
   [0.58308774 0.63785946 0.0373708 ]
   [0.6935075  0.46269396 0.00646839]]]]
[[[[0.59461343 0.6194672  0.6132345 ]
   [0.5840525  0.66445947 0.77779186]
   [0.5360247  0.5957732  0.59969795]
   [0.6198354  0.6691403  0.6006451 ]
   [0.5228641  0.51262826 0.6671141 ]
   [0.762328   0.71962214 0.5687571 ]
   [0.72822607 0.3005269  0.7844223 ]
   [0.77574277 0.7535884  0.0267247 ]
   [0.74683857 0.29168925 0.01071557]
   [0.758

[[[[0.56241393 0.576732   0.554673  ]
   [0.5257189  0.65026236 0.8494245 ]
   [0.48647416 0.5357035  0.707268  ]
   [0.5945199  0.68967444 0.65012074]
   [0.50587326 0.45603937 0.6107387 ]
   [0.7678518  0.7632965  0.5708068 ]
   [0.7376294  0.2778383  0.7483275 ]
   [0.7797839  0.8402889  0.02564666]
   [0.7783401  0.15563959 0.00559419]
   [0.7634395  0.8158044  0.03008488]
   [0.7316538  0.2604606  0.00822729]
   [0.793224   0.8727107  0.00790381]
   [0.81129575 0.25252855 0.00509116]
   [0.59848356 0.65515417 0.0058341 ]
   [0.7483052  0.2720613  0.03666782]
   [0.51225615 0.6173876  0.03980517]
   [0.46267036 0.4682001  0.01179183]]]]
[[[[0.5700635  0.56366605 0.7308452 ]
   [0.52318406 0.6432492  0.7730992 ]
   [0.48490214 0.51844674 0.73062384]
   [0.59192365 0.693864   0.74012464]
   [0.5024626  0.44366318 0.6095173 ]
   [0.77533835 0.7887705  0.39034405]
   [0.7426319  0.26188686 0.7686897 ]
   [0.7809637  0.8394166  0.01259348]
   [0.76442784 0.11699539 0.00231493]
   [0.755

[[[[0.5867444  0.5223208  0.71628654]
   [0.50977224 0.6112726  0.76517165]
   [0.48351803 0.47398904 0.6585877 ]
   [0.5694105  0.6822065  0.5962272 ]
   [0.49835384 0.41038665 0.5173147 ]
   [0.73441255 0.7881657  0.7801214 ]
   [0.7548644  0.24152763 0.7543436 ]
   [0.5318663  0.70881706 0.0431987 ]
   [0.4598621  0.41216695 0.03004834]
   [0.71900964 0.7536389  0.02904725]
   [0.76723325 0.24088722 0.00618812]
   [0.9836349  0.7507641  0.00471425]
   [0.809964   0.22869238 0.0108133 ]
   [0.740482   0.79759514 0.01399687]
   [0.75996995 0.24041331 0.03055015]
   [0.49824572 0.5896712  0.06686863]
   [0.44677567 0.41330984 0.01905888]]]]
[[[[0.5826854  0.52456707 0.7223806 ]
   [0.50930697 0.6106085  0.7103181 ]
   [0.4851903  0.47705415 0.7018551 ]
   [0.5640395  0.68117595 0.6824548 ]
   [0.4964406  0.40866706 0.4515017 ]
   [0.72335625 0.7852624  0.6577437 ]
   [0.7495094  0.24397519 0.76560855]
   [0.7600214  0.85313267 0.0292865 ]
   [0.4603332  0.41217324 0.0293538 ]
   [0.697

[[[[0.5810796  0.5400362  0.73312205]
   [0.51351863 0.60210097 0.7652854 ]
   [0.502665   0.49010408 0.757565  ]
   [0.54508406 0.6526855  0.61404717]
   [0.5178128  0.42375204 0.5867178 ]
   [0.73804104 0.76268834 0.53763115]
   [0.7380436  0.26802    0.74930567]
   [0.76553404 0.82595724 0.0320431 ]
   [0.76197064 0.24763624 0.00838622]
   [0.7572135  0.81534094 0.025103  ]
   [0.7656503  0.23908517 0.02014267]
   [0.42489234 0.81522536 0.01954809]
   [0.8056016  0.26266813 0.01152766]
   [0.7530431  0.7801631  0.01388302]
   [0.7511532  0.26195857 0.08510849]
   [0.4955302  0.57858944 0.05325931]
   [0.66315234 0.4889779  0.00505009]]]]
[[[[0.5833054  0.54043865 0.72178185]
   [0.5175228  0.60252583 0.71088773]
   [0.5080671  0.49000338 0.85192895]
   [0.54681456 0.6537978  0.58877766]
   [0.5211015  0.42284882 0.59863126]
   [0.738574   0.7640223  0.5239135 ]
   [0.7373782  0.27397424 0.756233  ]
   [0.7615472  0.8237433  0.02895027]
   [0.7660486  0.2427386  0.01384658]
   [0.752

[[[[0.5928324  0.5437598  0.6440956 ]
   [0.5263512  0.60416406 0.78177977]
   [0.51802886 0.49593902 0.6744839 ]
   [0.5525657  0.6572596  0.64386487]
   [0.5243022  0.4270442  0.70964193]
   [0.7488603  0.7795089  0.6931717 ]
   [0.73884684 0.2734546  0.7237436 ]
   [0.7639457  0.8214696  0.02370378]
   [0.7662921  0.25078565 0.01479176]
   [0.59946966 0.5914774  0.0653744 ]
   [0.75193554 0.3274875  0.03963652]
   [0.4427486  0.8192954  0.01396102]
   [0.8030064  0.26967496 0.01218298]
   [0.7610486  0.7943472  0.01411307]
   [0.7525643  0.26914218 0.07131687]
   [0.50748694 0.5757922  0.03537253]
   [0.6589768  0.48990682 0.00593969]]]]
[[[[0.58958906 0.5433841  0.6892544 ]
   [0.523726   0.6042987  0.84270215]
   [0.5154342  0.49589404 0.59699583]
   [0.5519989  0.65665877 0.6612992 ]
   [0.5227461  0.42842457 0.72995913]
   [0.7413451  0.7705773  0.6714072 ]
   [0.74097025 0.27192786 0.759175  ]
   [0.7597155  0.8093161  0.02228546]
   [0.7672438  0.24449676 0.00847581]
   [0.598

[[[[0.5886606  0.5507357  0.726583  ]
   [0.5262148  0.60805595 0.6747742 ]
   [0.5177707  0.5031546  0.65258825]
   [0.5574783  0.66201067 0.746056  ]
   [0.5286274  0.43461576 0.6333988 ]
   [0.7460228  0.77601117 0.6442513 ]
   [0.7418651  0.27285272 0.79805416]
   [0.7616794  0.81995016 0.02529582]
   [0.7665846  0.24416956 0.00776184]
   [0.5819417  0.5980668  0.06459048]
   [0.7649516  0.24025431 0.02813569]
   [0.9889141  0.729962   0.00387841]
   [0.40814528 0.81339693 0.04468903]
   [0.75816524 0.7927325  0.01385805]
   [0.7531366  0.26913738 0.07722425]
   [0.6788125  0.64441156 0.00604531]
   [0.6638405  0.49071312 0.00535256]]]]
[[[[0.5864282  0.5481534  0.66763765]
   [0.52448773 0.6078945  0.6453836 ]
   [0.5119095  0.49966067 0.6074232 ]
   [0.5585329  0.6610705  0.74294996]
   [0.52210844 0.4323665  0.7603996 ]
   [0.7398059  0.76930285 0.54954475]
   [0.73425883 0.2776615  0.7211863 ]
   [0.7604315  0.82178175 0.03075466]
   [0.7664482  0.25197747 0.01356685]
   [0.581

[[[[0.58880365 0.55096555 0.7305441 ]
   [0.52632546 0.60920835 0.7054652 ]
   [0.51639694 0.50395507 0.6439817 ]
   [0.5600356  0.65831304 0.6991098 ]
   [0.52587014 0.43551815 0.58451396]
   [0.74272203 0.76409733 0.59216154]
   [0.73893535 0.27117258 0.7985077 ]
   [0.76625025 0.8241868  0.02457824]
   [0.7615101  0.24862021 0.00956947]
   [0.5816845  0.5975643  0.06388721]
   [0.76323897 0.23988342 0.03463623]
   [0.4464042  0.81675833 0.01970345]
   [0.42269555 0.8138174  0.05046213]
   [0.75941634 0.78018916 0.00862637]
   [0.7489563  0.2699108  0.06973454]
   [0.6624828  0.6585879  0.00830624]
   [0.6656275  0.489143   0.00586706]]]]
[[[[0.5916818  0.55174583 0.64457965]
   [0.52768064 0.60873574 0.6682132 ]
   [0.5172663  0.5043621  0.69563246]
   [0.5571182  0.6597116  0.71603525]
   [0.5239682  0.4347133  0.7511685 ]
   [0.7417954  0.76742816 0.64220065]
   [0.7402151  0.27075407 0.8313925 ]
   [0.7656088  0.82422173 0.02940807]
   [0.7672269  0.24176821 0.008616  ]
   [0.582

[[[[0.55777323 0.5460467  0.6669967 ]
   [0.5056321  0.60481924 0.7819411 ]
   [0.48884147 0.5007423  0.7641477 ]
   [0.5535445  0.65672284 0.7107595 ]
   [0.51633775 0.43690965 0.6756714 ]
   [0.73686534 0.76760286 0.56707305]
   [0.7423078  0.26988083 0.72948   ]
   [0.7605958  0.8175021  0.0273762 ]
   [0.76824665 0.24365897 0.0091455 ]
   [0.74315894 0.8038575  0.02481845]
   [0.76244736 0.23834479 0.02543896]
   [0.9071068  0.7347987  0.00475937]
   [0.41032085 0.8130747  0.03999302]
   [0.75454605 0.78323686 0.01218233]
   [0.7561091  0.26680958 0.06907299]
   [0.63714904 0.6552886  0.00596684]
   [0.46181795 0.43577045 0.0165301 ]]]]
[[[[0.5534358  0.5497223  0.7559281 ]
   [0.50177664 0.605708   0.6495148 ]
   [0.48831022 0.50461936 0.8085331 ]
   [0.5524194  0.6561588  0.7147644 ]
   [0.5155028  0.43939844 0.52464974]
   [0.74093693 0.77296317 0.6527535 ]
   [0.7407414  0.27282086 0.765878  ]
   [0.7617105  0.8205902  0.03595376]
   [0.76781857 0.24467005 0.01214543]
   [0.750

[[[[0.5564181  0.5426818  0.7119184 ]
   [0.5056504  0.60166186 0.83561814]
   [0.4874059  0.49618387 0.8140576 ]
   [0.55797344 0.6516801  0.6265302 ]
   [0.51408863 0.43533218 0.6620936 ]
   [0.7413779  0.7649532  0.69837505]
   [0.7415078  0.26566836 0.87306315]
   [0.7590357  0.80841905 0.0362893 ]
   [0.48512116 0.44763163 0.03650957]
   [0.7417078  0.8009526  0.0311529 ]
   [0.7659607  0.23366688 0.02174702]
   [0.44534647 0.818588   0.02006161]
   [0.41063607 0.81138813 0.05846933]
   [0.75905615 0.78231114 0.02136245]
   [0.75375336 0.26348117 0.07872218]
   [0.63017464 0.63776964 0.00652882]
   [0.46320048 0.43562236 0.02199137]]]]
[[[[0.55657893 0.5416234  0.73407435]
   [0.5050918  0.60037684 0.82427406]
   [0.4883864  0.49563065 0.82083833]
   [0.55650216 0.65167147 0.6398431 ]
   [0.51428807 0.43463635 0.6690236 ]
   [0.7387172  0.7627261  0.6208774 ]
   [0.741369   0.26918572 0.7273197 ]
   [0.7577369  0.8090375  0.04422736]
   [0.7681319  0.23347738 0.00789174]
   [0.742

[[[[0.55684114 0.541288   0.73630553]
   [0.5057835  0.601701   0.837519  ]
   [0.48842964 0.49475098 0.8183578 ]
   [0.5592899  0.6518677  0.6257472 ]
   [0.5146117  0.4369437  0.6524631 ]
   [0.73675203 0.7599995  0.5664798 ]
   [0.73925567 0.26942936 0.69699913]
   [0.7568285  0.8087508  0.02880859]
   [0.46505806 0.42706817 0.04330355]
   [0.7461011  0.8051044  0.02522048]
   [0.7638822  0.23739854 0.02333373]
   [0.90901196 0.7337559  0.00455749]
   [0.39759564 0.80812645 0.03095469]
   [0.75521517 0.7767409  0.01343492]
   [0.75227225 0.2654095  0.06320047]
   [0.6300734  0.6372831  0.00650859]
   [0.46267083 0.43606997 0.02266827]]]]
[[[[0.5562289  0.5430476  0.7064402 ]
   [0.505208   0.6026865  0.81420255]
   [0.48806676 0.49505192 0.8177852 ]
   [0.5559402  0.65411043 0.68580896]
   [0.5140085  0.43621197 0.6573834 ]
   [0.7377678  0.7616145  0.59762156]
   [0.73939264 0.26824164 0.70283484]
   [0.7574878  0.8087883  0.02882129]
   [0.7698629  0.2339546  0.00802636]
   [0.744

[[[[0.555396   0.54122394 0.7293265 ]
   [0.5035201  0.60124975 0.78553414]
   [0.48740837 0.49517515 0.8133241 ]
   [0.55500054 0.65121156 0.6010054 ]
   [0.51294875 0.43933183 0.4440281 ]
   [0.73119366 0.7542973  0.7242073 ]
   [0.73795426 0.27501643 0.7744874 ]
   [0.757969   0.8076682  0.03361848]
   [0.7681292  0.24283144 0.01793662]
   [0.751442   0.80137587 0.02849662]
   [0.7655933  0.23854525 0.0376274 ]
   [0.45938325 0.81926364 0.019279  ]
   [0.46787438 0.82945484 0.04504722]
   [0.7517417  0.7748713  0.01401615]
   [0.74856776 0.27069485 0.06453288]
   [0.4936976  0.58812183 0.03697342]
   [0.4614859  0.4373587  0.01952791]]]]
[[[[0.5550609  0.5413474  0.7408052 ]
   [0.5028836  0.60102034 0.77252126]
   [0.486871   0.495423   0.82104814]
   [0.553224   0.6513358  0.6085095 ]
   [0.5106732  0.43858075 0.6958614 ]
   [0.73827624 0.7643291  0.61927855]
   [0.73929113 0.27372983 0.7207169 ]
   [0.7598704  0.81803536 0.03730619]
   [0.76971537 0.24357267 0.02098802]
   [0.745

[[[[0.5574431  0.54267657 0.70768046]
   [0.50418514 0.60186654 0.817467  ]
   [0.48964074 0.494653   0.8153379 ]
   [0.5537211  0.65340686 0.6435077 ]
   [0.51821774 0.43624    0.6563395 ]
   [0.7380367  0.758652   0.5879954 ]
   [0.7359336  0.27776864 0.75138414]
   [0.7582129  0.8065933  0.02513662]
   [0.7712076  0.24204513 0.02056924]
   [0.7508715  0.80645937 0.02032048]
   [0.7679706  0.23552236 0.04247767]
   [0.43204078 0.8157107  0.01458251]
   [0.47713524 0.8353732  0.02885869]
   [0.7560386  0.774766   0.01142535]
   [0.75158143 0.27119926 0.08777609]
   [0.6459968  0.6259995  0.00582963]
   [0.46059096 0.43580037 0.0192357 ]]]]
[[[[0.55689883 0.5432688  0.69948065]
   [0.50525236 0.6021878  0.82305   ]
   [0.4898717  0.4957539  0.7843404 ]
   [0.5569242  0.6531118  0.6757913 ]
   [0.5184791  0.43636167 0.6724866 ]
   [0.7400611  0.7586788  0.62650204]
   [0.7347987  0.27628848 0.7433244 ]
   [0.7585292  0.8085461  0.03351891]
   [0.769058   0.24391858 0.01455197]
   [0.751

[[[[0.5579176  0.58177096 0.72978747]
   [0.51212424 0.6280957  0.7824521 ]
   [0.49192873 0.52808493 0.7930454 ]
   [0.5551924  0.658511   0.64794123]
   [0.5254121  0.44830427 0.7547679 ]
   [0.7318827  0.7534609  0.7047417 ]
   [0.7335458  0.2766315  0.7912649 ]
   [0.76470983 0.8240955  0.02793804]
   [0.7675123  0.24270993 0.01018211]
   [0.75409013 0.81571877 0.01876068]
   [0.7550671  0.34169817 0.01717985]
   [0.8658956  0.7341309  0.00431439]
   [0.47171077 0.8336115  0.02415565]
   [0.75258225 0.76641625 0.00682941]
   [0.7443223  0.27305412 0.06230837]
   [0.5820141  0.6834117  0.01084408]
   [0.6801039  0.4352466  0.00700003]]]]
[[[[0.56025606 0.5779849  0.47793356]
   [0.509867   0.6245473  0.65946245]
   [0.4922021  0.5240741  0.84449005]
   [0.548442   0.66036016 0.64212114]
   [0.52420026 0.44980028 0.7580526 ]
   [0.73767215 0.7676127  0.5714488 ]
   [0.7328038  0.27339137 0.65226936]
   [0.76167953 0.819514   0.02615136]
   [0.7670099  0.24488433 0.00755531]
   [0.754

[[[[0.5515144  0.5441259  0.67229533]
   [0.4976001  0.5967458  0.5373479 ]
   [0.48655626 0.49461523 0.80774045]
   [0.5403977  0.643015   0.7025671 ]
   [0.51990277 0.4317548  0.7606975 ]
   [0.7327166  0.76123995 0.42843503]
   [0.7312707  0.27444658 0.71557224]
   [0.7598356  0.8196845  0.02631772]
   [0.7606691  0.24306624 0.00980002]
   [0.7506002  0.8049296  0.02130073]
   [0.7480731  0.3120371  0.01305896]
   [0.90750736 0.7310046  0.00327927]
   [0.42987558 0.8139137  0.03946984]
   [0.7443122  0.75673246 0.0065192 ]
   [0.743921   0.27267784 0.04738823]
   [0.6310189  0.62473005 0.00705895]
   [0.46461326 0.4333331  0.01422274]]]]
[[[[0.5568172  0.5418811  0.7239186 ]
   [0.49997565 0.59834814 0.6520659 ]
   [0.48735908 0.49156082 0.81546354]
   [0.5426831  0.64493364 0.7729702 ]
   [0.5146342  0.42932287 0.6120447 ]
   [0.7173335  0.73750174 0.71903574]
   [0.7281586  0.27743202 0.69558394]
   [0.7534544  0.81174505 0.03691375]
   [0.7693189  0.22889356 0.0101026 ]
   [0.746

In [22]:
# Demo function idea 

left_eye = keypoints_with_scores[0][0][1]
right_eye = keypoints_with_scores[0][0][2]

left_eye_y = np.array(left_eye[:2]*[480,640]).astype(int)[0]
right_eye_y = np.array(right_eye[:2]*[480,640]).astype(int)[0]

print(left_eye_y)
print(right_eye_y)
# threshold = 'smth'

# if left_eye_y-right_eye_y > threshold:
#     sound alarm 
    

256
237


In [ ]:
# load_model 

In [3]:
shaped = np.squeeze(np.multiply(interpreter.get_tensor(interpreter.get_output_details()[0]['index']), [480,640,1]))

In [4]:
for kp in shaped:
    ky, kx, kp_conf = kp
    print(int(ky), int(kx), kp_conf)

0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0
0 0 0.0


# 3. Draw Keypoints

In [5]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0,255,0), -1) 

# 4. Draw Edges

In [6]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [7]:
shaped[0], shaped[1]


(array([0., 0., 0.]), array([0., 0., 0.]))

In [8]:
for edge, color in EDGES.items():
    p1, p2 = edge
    y1, x1, c1 = shaped[p1]
    y2, x2, c2 = shaped[p2]
    print((int(x2), int(y2)))

(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)


In [9]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)